// Package extraction defines types for LLM-based entity extraction schemas.
// These types are generated by protoc-gen-entitystore from proto annotations
// and comments, and are designed to be consumed by LLM frameworks like Genkit.
package extraction

import "sync"

// ExtractionSchema describes an entity type for LLM-based extraction.
// Generated by protoc-gen-entitystore from proto annotations and comments.
type ExtractionSchema struct {
	// EntityType is the fully qualified proto message name.
	EntityType string `json:"entity_type"`

	// DisplayName is the human-friendly name (e.g., "Job Posting").
	DisplayName string `json:"display_name"`

	// Prompt is the system-level extraction instruction.
	Prompt string `json:"prompt,omitempty"`

	// Instructions are additional instructions appended after the schema.
	Instructions string `json:"instructions,omitempty"`

	// Fields describes each extractable field.
	Fields []ExtractionField `json:"fields"`
}

// ExtractionField describes a single field for LLM extraction.
type ExtractionField struct {
	// Name is the proto field name (snake_case).
	Name string `json:"name"`

	// Description is the human-readable field description.
	Description string `json:"description"`

	// Hint is an additional extraction directive for the LLM.
	Hint string `json:"hint,omitempty"`

	// Type is the expected output type (string, number, boolean, date, array).
	Type ExtractionFieldType `json:"type"`

	// Required indicates the field must be present in extraction output.
	// Derived from: anchor fields are required; others are optional.
	Required bool `json:"required"`

	// Repeated indicates the proto field is repeated (list).
	Repeated bool `json:"repeated"`

	// Examples are sample values for few-shot grounding.
	Examples []string `json:"examples,omitempty"`
}

// ExtractionFieldType identifies the expected output type for an extraction field.
type ExtractionFieldType string

const (
	ExtractionFieldTypeString  ExtractionFieldType = "string"
	ExtractionFieldTypeNumber  ExtractionFieldType = "number"
	ExtractionFieldTypeBoolean ExtractionFieldType = "boolean"
	ExtractionFieldTypeDate    ExtractionFieldType = "date"
	ExtractionFieldTypeArray   ExtractionFieldType = "array"
)

// ---------------------------------------------------------------------------
// Extraction schema registry
// ---------------------------------------------------------------------------

// ExtractionSchemaRegistry maps entity type names to their extraction schemas.
type ExtractionSchemaRegistry struct {
	mu      sync.RWMutex
	schemas map[string]ExtractionSchema
}

// NewExtractionSchemaRegistry creates an empty registry.
func NewExtractionSchemaRegistry() *ExtractionSchemaRegistry {
	return &ExtractionSchemaRegistry{schemas: make(map[string]ExtractionSchema)}
}

// Register adds or replaces a schema for the given entity type.
func (r *ExtractionSchemaRegistry) Register(s ExtractionSchema) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.schemas[s.EntityType] = s
}

// Get returns the schema for the given entity type, if registered.
func (r *ExtractionSchemaRegistry) Get(entityType string) (ExtractionSchema, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	s, ok := r.schemas[entityType]
	return s, ok
}

// All returns a copy of all registered schemas.
func (r *ExtractionSchemaRegistry) All() map[string]ExtractionSchema {
	r.mu.RLock()
	defer r.mu.RUnlock()
	out := make(map[string]ExtractionSchema, len(r.schemas))
	for k, v := range r.schemas {
		out[k] = v
	}
	return out
}
