// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anchors.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteAnchorsForEntity = `-- name: DeleteAnchorsForEntity :exec
DELETE FROM entity_anchors WHERE entity_id = $1
`

func (q *Queries) DeleteAnchorsForEntity(ctx context.Context, entityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnchorsForEntity, entityID)
	return err
}

const findByAnchors = `-- name: FindByAnchors :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_anchors a
JOIN entities e ON e.id = a.entity_id
WHERE a.entity_type = $1 AND a.anchor_field = $2 AND a.normalized_value = $3
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
  AND (cardinality($5::text[]) = 0 OR e.tags && $5::text[])
  AND ($6 = '' OR NOT ($6 = ANY(e.tags)) OR e.tags && $7::text[])
`

type FindByAnchorsParams struct {
	EntityType      string      `json:"entity_type"`
	AnchorField     string      `json:"anchor_field"`
	NormalizedValue string      `json:"normalized_value"`
	Tags            []string    `json:"tags"`
	AnyTags         []string    `json:"any_tags"`
	ExcludeTag      interface{} `json:"exclude_tag"`
	UnlessTags      []string    `json:"unless_tags"`
}

type FindByAnchorsRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindByAnchors(ctx context.Context, arg FindByAnchorsParams) ([]FindByAnchorsRow, error) {
	rows, err := q.db.Query(ctx, findByAnchors,
		arg.EntityType,
		arg.AnchorField,
		arg.NormalizedValue,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByAnchorsRow
	for rows.Next() {
		var i FindByAnchorsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnchor = `-- name: UpsertAnchor :exec
INSERT INTO entity_anchors (entity_id, entity_type, anchor_field, normalized_value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (entity_type, anchor_field, normalized_value) DO UPDATE
SET entity_id = EXCLUDED.entity_id
`

type UpsertAnchorParams struct {
	EntityID        uuid.UUID `json:"entity_id"`
	EntityType      string    `json:"entity_type"`
	AnchorField     string    `json:"anchor_field"`
	NormalizedValue string    `json:"normalized_value"`
}

func (q *Queries) UpsertAnchor(ctx context.Context, arg UpsertAnchorParams) error {
	_, err := q.db.Exec(ctx, upsertAnchor,
		arg.EntityID,
		arg.EntityType,
		arg.AnchorField,
		arg.NormalizedValue,
	)
	return err
}
