// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumer.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConsumerCursor = `-- name: AdvanceConsumerCursor :exec
UPDATE entity_event_consumers
SET last_event_at = $1,
    last_event_id = $2,
    updated_at = now()
WHERE name = $3 AND holder_id = $4
`

type AdvanceConsumerCursorParams struct {
	LastEventAt time.Time   `json:"last_event_at"`
	LastEventID pgtype.UUID `json:"last_event_id"`
	Name        string      `json:"name"`
	HolderID    pgtype.Text `json:"holder_id"`
}

func (q *Queries) AdvanceConsumerCursor(ctx context.Context, arg AdvanceConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, advanceConsumerCursor,
		arg.LastEventAt,
		arg.LastEventID,
		arg.Name,
		arg.HolderID,
	)
	return err
}

const getConsumerCursor = `-- name: GetConsumerCursor :one
SELECT last_event_at, last_event_id, holder_id, acquired_at, expires_at, updated_at
FROM entity_event_consumers
WHERE name = $1
`

type GetConsumerCursorRow struct {
	LastEventAt time.Time          `json:"last_event_at"`
	LastEventID pgtype.UUID        `json:"last_event_id"`
	HolderID    pgtype.Text        `json:"holder_id"`
	AcquiredAt  pgtype.Timestamptz `json:"acquired_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) GetConsumerCursor(ctx context.Context, name string) (GetConsumerCursorRow, error) {
	row := q.db.QueryRow(ctx, getConsumerCursor, name)
	var i GetConsumerCursorRow
	err := row.Scan(
		&i.LastEventAt,
		&i.LastEventID,
		&i.HolderID,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsAfterCursor = `-- name: GetEventsAfterCursor :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, occurred_at, published_at
FROM entity_events
WHERE occurred_at > $1
   OR (occurred_at = $1 AND id > $2)
ORDER BY occurred_at, id
LIMIT $3
`

type GetEventsAfterCursorParams struct {
	AfterAt   time.Time `json:"after_at"`
	AfterID   uuid.UUID `json:"after_id"`
	BatchSize int32     `json:"batch_size"`
}

func (q *Queries) GetEventsAfterCursor(ctx context.Context, arg GetEventsAfterCursorParams) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getEventsAfterCursor, arg.AfterAt, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumers = `-- name: ListConsumers :many
SELECT name, last_event_at, last_event_id, holder_id, acquired_at, expires_at, updated_at
FROM entity_event_consumers
ORDER BY name
`

func (q *Queries) ListConsumers(ctx context.Context) ([]EntityEventConsumer, error) {
	rows, err := q.db.Query(ctx, listConsumers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEventConsumer
	for rows.Next() {
		var i EntityEventConsumer
		if err := rows.Scan(
			&i.Name,
			&i.LastEventAt,
			&i.LastEventID,
			&i.HolderID,
			&i.AcquiredAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseConsumerLock = `-- name: ReleaseConsumerLock :exec
UPDATE entity_event_consumers
SET holder_id = NULL, expires_at = NULL
WHERE name = $1 AND holder_id = $2
`

type ReleaseConsumerLockParams struct {
	Name     string      `json:"name"`
	HolderID pgtype.Text `json:"holder_id"`
}

func (q *Queries) ReleaseConsumerLock(ctx context.Context, arg ReleaseConsumerLockParams) error {
	_, err := q.db.Exec(ctx, releaseConsumerLock, arg.Name, arg.HolderID)
	return err
}

const renewConsumerLock = `-- name: RenewConsumerLock :execresult
UPDATE entity_event_consumers
SET expires_at = now() + $1::interval
WHERE name = $2 AND holder_id = $3
`

type RenewConsumerLockParams struct {
	Ttl      pgtype.Interval `json:"ttl"`
	Name     string          `json:"name"`
	HolderID pgtype.Text     `json:"holder_id"`
}

func (q *Queries) RenewConsumerLock(ctx context.Context, arg RenewConsumerLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, renewConsumerLock, arg.Ttl, arg.Name, arg.HolderID)
}

const tryAcquireConsumerLock = `-- name: TryAcquireConsumerLock :execresult
INSERT INTO entity_event_consumers (name, holder_id, acquired_at, expires_at)
VALUES ($1, $2, now(), now() + $3::interval)
ON CONFLICT (name) DO UPDATE
SET holder_id = EXCLUDED.holder_id,
    acquired_at = now(),
    expires_at = EXCLUDED.expires_at
WHERE entity_event_consumers.expires_at IS NULL
   OR entity_event_consumers.expires_at < now()
`

type TryAcquireConsumerLockParams struct {
	Name     string          `json:"name"`
	HolderID pgtype.Text     `json:"holder_id"`
	Ttl      pgtype.Interval `json:"ttl"`
}

func (q *Queries) TryAcquireConsumerLock(ctx context.Context, arg TryAcquireConsumerLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, tryAcquireConsumerLock, arg.Name, arg.HolderID, arg.Ttl)
}
