// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumer.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConsumerCursor = `-- name: AdvanceConsumerCursor :exec
UPDATE entity_event_consumers
SET last_event_at = $1,
    last_event_id = $2,
    consecutive_failures = 0,
    last_error = NULL,
    backoff_until = NULL,
    updated_at = now()
WHERE name = $3 AND holder_id = $4
`

type AdvanceConsumerCursorParams struct {
	LastEventAt time.Time   `json:"last_event_at"`
	LastEventID pgtype.UUID `json:"last_event_id"`
	Name        string      `json:"name"`
	HolderID    pgtype.Text `json:"holder_id"`
}

func (q *Queries) AdvanceConsumerCursor(ctx context.Context, arg AdvanceConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, advanceConsumerCursor,
		arg.LastEventAt,
		arg.LastEventID,
		arg.Name,
		arg.HolderID,
	)
	return err
}

const getConsumerCursor = `-- name: GetConsumerCursor :one
SELECT last_event_at, last_event_id, holder_id, acquired_at, expires_at, updated_at,
       consecutive_failures, last_error, backoff_until
FROM entity_event_consumers
WHERE name = $1
`

type GetConsumerCursorRow struct {
	LastEventAt         time.Time          `json:"last_event_at"`
	LastEventID         pgtype.UUID        `json:"last_event_id"`
	HolderID            pgtype.Text        `json:"holder_id"`
	AcquiredAt          pgtype.Timestamptz `json:"acquired_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	BackoffUntil        pgtype.Timestamptz `json:"backoff_until"`
}

func (q *Queries) GetConsumerCursor(ctx context.Context, name string) (GetConsumerCursorRow, error) {
	row := q.db.QueryRow(ctx, getConsumerCursor, name)
	var i GetConsumerCursorRow
	err := row.Scan(
		&i.LastEventAt,
		&i.LastEventID,
		&i.HolderID,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.ConsecutiveFailures,
		&i.LastError,
		&i.BackoffUntil,
	)
	return i, err
}

const getEventsAfterCursor = `-- name: GetEventsAfterCursor :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, entity_type, occurred_at, published_at
FROM entity_events
WHERE occurred_at > $1
   OR (occurred_at = $1 AND id > $2)
ORDER BY occurred_at, id
LIMIT $3
`

type GetEventsAfterCursorParams struct {
	AfterAt   time.Time `json:"after_at"`
	AfterID   uuid.UUID `json:"after_id"`
	BatchSize int32     `json:"batch_size"`
}

type GetEventsAfterCursorRow struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadType string             `json:"payload_type"`
	Payload     json.RawMessage    `json:"payload"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RelationKey pgtype.Text        `json:"relation_key"`
	Tags        []string           `json:"tags"`
	EntityType  string             `json:"entity_type"`
	OccurredAt  time.Time          `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetEventsAfterCursor(ctx context.Context, arg GetEventsAfterCursorParams) ([]GetEventsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, getEventsAfterCursor, arg.AfterAt, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsAfterCursorRow
	for rows.Next() {
		var i GetEventsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.EntityType,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumers = `-- name: ListConsumers :many
SELECT name, last_event_at, last_event_id, holder_id, acquired_at, expires_at, updated_at,
       consecutive_failures, last_error, backoff_until
FROM entity_event_consumers
ORDER BY name
`

func (q *Queries) ListConsumers(ctx context.Context) ([]EntityEventConsumer, error) {
	rows, err := q.db.Query(ctx, listConsumers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEventConsumer
	for rows.Next() {
		var i EntityEventConsumer
		if err := rows.Scan(
			&i.Name,
			&i.LastEventAt,
			&i.LastEventID,
			&i.HolderID,
			&i.AcquiredAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.BackoffUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseConsumerLock = `-- name: ReleaseConsumerLock :exec
UPDATE entity_event_consumers
SET holder_id = NULL, expires_at = NULL
WHERE name = $1 AND holder_id = $2
`

type ReleaseConsumerLockParams struct {
	Name     string      `json:"name"`
	HolderID pgtype.Text `json:"holder_id"`
}

func (q *Queries) ReleaseConsumerLock(ctx context.Context, arg ReleaseConsumerLockParams) error {
	_, err := q.db.Exec(ctx, releaseConsumerLock, arg.Name, arg.HolderID)
	return err
}

const renewConsumerLock = `-- name: RenewConsumerLock :execresult
UPDATE entity_event_consumers
SET expires_at = now() + $1::interval
WHERE name = $2 AND holder_id = $3
`

type RenewConsumerLockParams struct {
	Ttl      pgtype.Interval `json:"ttl"`
	Name     string          `json:"name"`
	HolderID pgtype.Text     `json:"holder_id"`
}

func (q *Queries) RenewConsumerLock(ctx context.Context, arg RenewConsumerLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, renewConsumerLock, arg.Ttl, arg.Name, arg.HolderID)
}

const tryAcquireConsumerLock = `-- name: TryAcquireConsumerLock :execresult
INSERT INTO entity_event_consumers (name, holder_id, acquired_at, expires_at)
VALUES ($1, $2, now(), now() + $3::interval)
ON CONFLICT (name) DO UPDATE
SET holder_id = EXCLUDED.holder_id,
    acquired_at = now(),
    expires_at = EXCLUDED.expires_at
WHERE entity_event_consumers.expires_at IS NULL
   OR entity_event_consumers.expires_at < now()
`

type TryAcquireConsumerLockParams struct {
	Name     string          `json:"name"`
	HolderID pgtype.Text     `json:"holder_id"`
	Ttl      pgtype.Interval `json:"ttl"`
}

func (q *Queries) TryAcquireConsumerLock(ctx context.Context, arg TryAcquireConsumerLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, tryAcquireConsumerLock, arg.Name, arg.HolderID, arg.Ttl)
}

const updateConsumerFailureState = `-- name: UpdateConsumerFailureState :exec
UPDATE entity_event_consumers
SET consecutive_failures = $1,
    last_error = $2,
    backoff_until = $3::timestamptz,
    updated_at = now()
WHERE name = $4 AND holder_id = $5
`

type UpdateConsumerFailureStateParams struct {
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	BackoffUntil        pgtype.Timestamptz `json:"backoff_until"`
	Name                string             `json:"name"`
	HolderID            pgtype.Text        `json:"holder_id"`
}

func (q *Queries) UpdateConsumerFailureState(ctx context.Context, arg UpdateConsumerFailureStateParams) error {
	_, err := q.db.Exec(ctx, updateConsumerFailureState,
		arg.ConsecutiveFailures,
		arg.LastError,
		arg.BackoffUntil,
		arg.Name,
		arg.HolderID,
	)
	return err
}
