// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deadletter.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDeadLetters = `-- name: CountDeadLetters :one
SELECT COUNT(*) FROM entity_event_dead_letters WHERE consumer_name = $1
`

func (q *Queries) CountDeadLetters(ctx context.Context, consumerName string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeadLetters, consumerName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadLetter = `-- name: DeleteDeadLetter :exec
DELETE FROM entity_event_dead_letters WHERE id = $1
`

func (q *Queries) DeleteDeadLetter(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeadLetter, id)
	return err
}

const deleteDeadLettersByConsumer = `-- name: DeleteDeadLettersByConsumer :exec
DELETE FROM entity_event_dead_letters WHERE consumer_name = $1
`

func (q *Queries) DeleteDeadLettersByConsumer(ctx context.Context, consumerName string) error {
	_, err := q.db.Exec(ctx, deleteDeadLettersByConsumer, consumerName)
	return err
}

const getDeadLetter = `-- name: GetDeadLetter :one
SELECT id, consumer_name, event_id, event_type, payload_type, entity_id, payload, error_message, retry_count, created_at FROM entity_event_dead_letters WHERE id = $1
`

func (q *Queries) GetDeadLetter(ctx context.Context, id int64) (EntityEventDeadLetter, error) {
	row := q.db.QueryRow(ctx, getDeadLetter, id)
	var i EntityEventDeadLetter
	err := row.Scan(
		&i.ID,
		&i.ConsumerName,
		&i.EventID,
		&i.EventType,
		&i.PayloadType,
		&i.EntityID,
		&i.Payload,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeadLetter = `-- name: InsertDeadLetter :exec
INSERT INTO entity_event_dead_letters (consumer_name, event_id, event_type, payload_type, entity_id, payload, error_message, retry_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDeadLetterParams struct {
	ConsumerName string      `json:"consumer_name"`
	EventID      uuid.UUID   `json:"event_id"`
	EventType    string      `json:"event_type"`
	PayloadType  string      `json:"payload_type"`
	EntityID     pgtype.Text `json:"entity_id"`
	Payload      []byte      `json:"payload"`
	ErrorMessage string      `json:"error_message"`
	RetryCount   int32       `json:"retry_count"`
}

func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error {
	_, err := q.db.Exec(ctx, insertDeadLetter,
		arg.ConsumerName,
		arg.EventID,
		arg.EventType,
		arg.PayloadType,
		arg.EntityID,
		arg.Payload,
		arg.ErrorMessage,
		arg.RetryCount,
	)
	return err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id, consumer_name, event_id, event_type, payload_type, entity_id, payload, error_message, retry_count, created_at FROM entity_event_dead_letters
WHERE consumer_name = $1
  AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
ORDER BY created_at DESC
LIMIT $3
`

type ListDeadLettersParams struct {
	ConsumerName string   `json:"consumer_name"`
	EventTypes   []string `json:"event_types"`
	MaxResults   int32    `json:"max_results"`
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]EntityEventDeadLetter, error) {
	rows, err := q.db.Query(ctx, listDeadLetters, arg.ConsumerName, arg.EventTypes, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEventDeadLetter
	for rows.Next() {
		var i EntityEventDeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerName,
			&i.EventID,
			&i.EventType,
			&i.PayloadType,
			&i.EntityID,
			&i.Payload,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldDeadLetters = `-- name: PurgeOldDeadLetters :exec
DELETE FROM entity_event_dead_letters WHERE created_at < $1
`

func (q *Queries) PurgeOldDeadLetters(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, purgeOldDeadLetters, createdAt)
	return err
}
