// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const findByEmbedding = `-- name: FindByEmbedding :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entities e
WHERE (cardinality($1::text[]) = 0 OR e.entity_type = ANY($1))
  AND e.embedding IS NOT NULL
  AND (cardinality($2::text[]) = 0 OR e.tags @> $2::text[])
ORDER BY e.embedding <=> $3::vector
LIMIT $4
`

type FindByEmbeddingParams struct {
	EntityTypes []string        `json:"entity_types"`
	Tags        []string        `json:"tags"`
	Embedding   pgvector.Vector `json:"embedding"`
	TopK        int32           `json:"top_k"`
}

type FindByEmbeddingRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindByEmbedding(ctx context.Context, arg FindByEmbeddingParams) ([]FindByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, findByEmbedding,
		arg.EntityTypes,
		arg.Tags,
		arg.Embedding,
		arg.TopK,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByEmbeddingRow
	for rows.Next() {
		var i FindByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntityEmbedding = `-- name: UpdateEntityEmbedding :exec
UPDATE entities
SET embedding = $1::vector, updated_at = now()
WHERE id = $2
`

type UpdateEntityEmbeddingParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	EntityID  uuid.UUID       `json:"entity_id"`
}

func (q *Queries) UpdateEntityEmbedding(ctx context.Context, arg UpdateEntityEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateEntityEmbedding, arg.Embedding, arg.EntityID)
	return err
}
