// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllEntities = `-- name: CountAllEntities :one
SELECT count(*) FROM entities WHERE deleted_at IS NULL
`

func (q *Queries) CountAllEntities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllEntities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllRelations = `-- name: CountAllRelations :one
SELECT count(*) FROM entity_relations
`

func (q *Queries) CountAllRelations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllRelations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntitiesByType = `-- name: CountEntitiesByType :one
SELECT count(*) FROM entities WHERE entity_type = $1 AND deleted_at IS NULL
`

func (q *Queries) CountEntitiesByType(ctx context.Context, entityType string) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesByType, entityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntityTypes = `-- name: CountEntityTypes :many
SELECT entity_type, count(*) AS count FROM entities WHERE deleted_at IS NULL GROUP BY entity_type ORDER BY count DESC
`

type CountEntityTypesRow struct {
	EntityType string `json:"entity_type"`
	Count      int64  `json:"count"`
}

func (q *Queries) CountEntityTypes(ctx context.Context) ([]CountEntityTypesRow, error) {
	rows, err := q.db.Query(ctx, countEntityTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEntityTypesRow
	for rows.Next() {
		var i CountEntityTypesRow
		if err := rows.Scan(&i.EntityType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRelationTypes = `-- name: CountRelationTypes :many
SELECT relation_type, count(*) AS count FROM entity_relations GROUP BY relation_type ORDER BY count DESC
`

type CountRelationTypesRow struct {
	RelationType string `json:"relation_type"`
	Count        int64  `json:"count"`
}

func (q *Queries) CountRelationTypes(ctx context.Context) ([]CountRelationTypesRow, error) {
	rows, err := q.db.Query(ctx, countRelationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRelationTypesRow
	for rows.Next() {
		var i CountRelationTypesRow
		if err := rows.Scan(&i.RelationType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRelationsForEntity = `-- name: CountRelationsForEntity :one
SELECT count(*) FROM entity_relations WHERE (source_id = $1 OR target_id = $1)
`

func (q *Queries) CountRelationsForEntity(ctx context.Context, entityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelationsForEntity, entityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSoftDeleted = `-- name: CountSoftDeleted :one
SELECT count(*) FROM entities WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountSoftDeleted(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSoftDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntity = `-- name: DeleteEntity :exec
UPDATE entities SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntity, id)
	return err
}

const getEntitiesByType = `-- name: GetEntitiesByType :many
SELECT id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
FROM entities
WHERE entity_type = $1
  AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL OR updated_at < $2::timestamptz)
ORDER BY updated_at DESC
LIMIT $3
`

type GetEntitiesByTypeParams struct {
	EntityType string             `json:"entity_type"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	PageSize   int32              `json:"page_size"`
}

type GetEntitiesByTypeRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) GetEntitiesByType(ctx context.Context, arg GetEntitiesByTypeParams) ([]GetEntitiesByTypeRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesByType, arg.EntityType, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntitiesByTypeRow
	for rows.Next() {
		var i GetEntitiesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.DisplayName,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesByTypeFiltered = `-- name: GetEntitiesByTypeFiltered :many
SELECT id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
FROM entities
WHERE entity_type = $1
  AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL OR updated_at < $2::timestamptz)
  AND (cardinality($3::text[]) = 0 OR tags @> $3::text[])
  AND (cardinality($4::text[]) = 0 OR tags && $4::text[])
  AND ($5 = '' OR NOT ($5 = ANY(tags)) OR tags && $6::text[])
ORDER BY updated_at DESC
LIMIT $7
`

type GetEntitiesByTypeFilteredParams struct {
	EntityType string             `json:"entity_type"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	Tags       []string           `json:"tags"`
	AnyTags    []string           `json:"any_tags"`
	ExcludeTag interface{}        `json:"exclude_tag"`
	UnlessTags []string           `json:"unless_tags"`
	PageSize   int32              `json:"page_size"`
}

type GetEntitiesByTypeFilteredRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) GetEntitiesByTypeFiltered(ctx context.Context, arg GetEntitiesByTypeFilteredParams) ([]GetEntitiesByTypeFilteredRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesByTypeFiltered,
		arg.EntityType,
		arg.Cursor,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntitiesByTypeFilteredRow
	for rows.Next() {
		var i GetEntitiesByTypeFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.DisplayName,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
FROM entities
WHERE id = $1 AND deleted_at IS NULL
`

type GetEntityRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) GetEntity(ctx context.Context, id uuid.UUID) (GetEntityRow, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i GetEntityRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.DisplayName,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteEntity = `-- name: HardDeleteEntity :exec
DELETE FROM entities WHERE id = $1
`

func (q *Queries) HardDeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEntity, id)
	return err
}

const insertEntity = `-- name: InsertEntity :one
INSERT INTO entities (entity_type, data, confidence, tags, display_name, version)
VALUES ($1, $2, $3, $4, $5, 0)
RETURNING id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
`

type InsertEntityParams struct {
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
}

type InsertEntityRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) (InsertEntityRow, error) {
	row := q.db.QueryRow(ctx, insertEntity,
		arg.EntityType,
		arg.Data,
		arg.Confidence,
		arg.Tags,
		arg.DisplayName,
	)
	var i InsertEntityRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.DisplayName,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEntityWithID = `-- name: InsertEntityWithID :one
INSERT INTO entities (id, entity_type, data, confidence, tags, display_name, version)
VALUES ($1, $2, $3, $4, $5, $6, 0)
RETURNING id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
`

type InsertEntityWithIDParams struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
}

type InsertEntityWithIDRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEntityWithID(ctx context.Context, arg InsertEntityWithIDParams) (InsertEntityWithIDRow, error) {
	row := q.db.QueryRow(ctx, insertEntityWithID,
		arg.ID,
		arg.EntityType,
		arg.Data,
		arg.Confidence,
		arg.Tags,
		arg.DisplayName,
	)
	var i InsertEntityWithIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.DisplayName,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeEntityData = `-- name: MergeEntityData :execresult
UPDATE entities
SET data = data || $2, confidence = $3, display_name = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $5 AND deleted_at IS NULL
`

type MergeEntityDataParams struct {
	ID              uuid.UUID       `json:"id"`
	Data            json.RawMessage `json:"data"`
	Confidence      float64         `json:"confidence"`
	DisplayName     string          `json:"display_name"`
	ExpectedVersion int32           `json:"expected_version"`
}

func (q *Queries) MergeEntityData(ctx context.Context, arg MergeEntityDataParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, mergeEntityData,
		arg.ID,
		arg.Data,
		arg.Confidence,
		arg.DisplayName,
		arg.ExpectedVersion,
	)
}

const searchByDisplayName = `-- name: SearchByDisplayName :many
SELECT id, entity_type, data, confidence, tags, display_name, version, created_at, updated_at
FROM entities
WHERE display_name ILIKE '%' || $1 || '%'
  AND deleted_at IS NULL
  AND (cardinality($2::text[]) = 0 OR tags @> $2::text[])
ORDER BY similarity(display_name, $1) DESC, updated_at DESC
LIMIT $3
`

type SearchByDisplayNameParams struct {
	Query      pgtype.Text `json:"query"`
	Tags       []string    `json:"tags"`
	MaxResults int32       `json:"max_results"`
}

type SearchByDisplayNameRow struct {
	ID          uuid.UUID       `json:"id"`
	EntityType  string          `json:"entity_type"`
	Data        json.RawMessage `json:"data"`
	Confidence  float64         `json:"confidence"`
	Tags        []string        `json:"tags"`
	DisplayName string          `json:"display_name"`
	Version     int32           `json:"version"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) SearchByDisplayName(ctx context.Context, arg SearchByDisplayNameParams) ([]SearchByDisplayNameRow, error) {
	rows, err := q.db.Query(ctx, searchByDisplayName, arg.Query, arg.Tags, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByDisplayNameRow
	for rows.Next() {
		var i SearchByDisplayNameRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.DisplayName,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntityData = `-- name: UpdateEntityData :execresult
UPDATE entities
SET data = $2, confidence = $3, display_name = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $5 AND deleted_at IS NULL
`

type UpdateEntityDataParams struct {
	ID              uuid.UUID       `json:"id"`
	Data            json.RawMessage `json:"data"`
	Confidence      float64         `json:"confidence"`
	DisplayName     string          `json:"display_name"`
	ExpectedVersion int32           `json:"expected_version"`
}

func (q *Queries) UpdateEntityData(ctx context.Context, arg UpdateEntityDataParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateEntityData,
		arg.ID,
		arg.Data,
		arg.Confidence,
		arg.DisplayName,
		arg.ExpectedVersion,
	)
}
