// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities WHERE id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntity, id)
	return err
}

const getEntitiesByType = `-- name: GetEntitiesByType :many
SELECT id, entity_type, data, confidence, tags, created_at, updated_at
FROM entities
WHERE entity_type = $1
  AND ($2::timestamptz IS NULL OR updated_at < $2::timestamptz)
ORDER BY updated_at DESC
LIMIT $3
`

type GetEntitiesByTypeParams struct {
	EntityType string             `json:"entity_type"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	PageSize   int32              `json:"page_size"`
}

type GetEntitiesByTypeRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) GetEntitiesByType(ctx context.Context, arg GetEntitiesByTypeParams) ([]GetEntitiesByTypeRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesByType, arg.EntityType, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntitiesByTypeRow
	for rows.Next() {
		var i GetEntitiesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT id, entity_type, data, confidence, tags, created_at, updated_at
FROM entities
WHERE id = $1
`

type GetEntityRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) GetEntity(ctx context.Context, id uuid.UUID) (GetEntityRow, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i GetEntityRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEntity = `-- name: InsertEntity :one
INSERT INTO entities (entity_type, data, confidence, tags)
VALUES ($1, $2, $3, $4)
RETURNING id, entity_type, data, confidence, tags, created_at, updated_at
`

type InsertEntityParams struct {
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
}

type InsertEntityRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) (InsertEntityRow, error) {
	row := q.db.QueryRow(ctx, insertEntity,
		arg.EntityType,
		arg.Data,
		arg.Confidence,
		arg.Tags,
	)
	var i InsertEntityRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEntityWithID = `-- name: InsertEntityWithID :one
INSERT INTO entities (id, entity_type, data, confidence, tags)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, entity_type, data, confidence, tags, created_at, updated_at
`

type InsertEntityWithIDParams struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
}

type InsertEntityWithIDRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEntityWithID(ctx context.Context, arg InsertEntityWithIDParams) (InsertEntityWithIDRow, error) {
	row := q.db.QueryRow(ctx, insertEntityWithID,
		arg.ID,
		arg.EntityType,
		arg.Data,
		arg.Confidence,
		arg.Tags,
	)
	var i InsertEntityWithIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Data,
		&i.Confidence,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeEntityData = `-- name: MergeEntityData :exec
UPDATE entities
SET data = data || $2, confidence = $3, updated_at = now()
WHERE id = $1
`

type MergeEntityDataParams struct {
	ID         uuid.UUID       `json:"id"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
}

func (q *Queries) MergeEntityData(ctx context.Context, arg MergeEntityDataParams) error {
	_, err := q.db.Exec(ctx, mergeEntityData, arg.ID, arg.Data, arg.Confidence)
	return err
}

const updateEntityData = `-- name: UpdateEntityData :exec
UPDATE entities
SET data = $2, confidence = $3, updated_at = now()
WHERE id = $1
`

type UpdateEntityDataParams struct {
	ID         uuid.UUID       `json:"id"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
}

func (q *Queries) UpdateEntityData(ctx context.Context, arg UpdateEntityDataParams) error {
	_, err := q.db.Exec(ctx, updateEntityData, arg.ID, arg.Data, arg.Confidence)
	return err
}
