// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT ev.id, ev.event_type, ev.payload_type, ev.payload, ev.entity_id, ev.relation_key, ev.tags, ev.entity_type, ev.occurred_at, ev.published_at,
       COALESCE(e.display_name, '') AS entity_display_name
FROM entity_events ev
LEFT JOIN entities e ON e.id = ev.entity_id
WHERE (cardinality($1::text[]) = 0 OR ev.event_type = ANY($1))
  AND ($2::timestamptz IS NULL OR ev.occurred_at < $2::timestamptz)
ORDER BY ev.occurred_at DESC
LIMIT $3
`

type GetAllEventsParams struct {
	EventTypes []string           `json:"event_types"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	MaxResults int32              `json:"max_results"`
}

type GetAllEventsRow struct {
	ID                uuid.UUID          `json:"id"`
	EventType         string             `json:"event_type"`
	PayloadType       string             `json:"payload_type"`
	Payload           json.RawMessage    `json:"payload"`
	EntityID          pgtype.UUID        `json:"entity_id"`
	RelationKey       pgtype.Text        `json:"relation_key"`
	Tags              []string           `json:"tags"`
	EntityType        string             `json:"entity_type"`
	OccurredAt        time.Time          `json:"occurred_at"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	EntityDisplayName string             `json:"entity_display_name"`
}

func (q *Queries) GetAllEvents(ctx context.Context, arg GetAllEventsParams) ([]GetAllEventsRow, error) {
	rows, err := q.db.Query(ctx, getAllEvents, arg.EventTypes, arg.Cursor, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.EntityType,
			&i.OccurredAt,
			&i.PublishedAt,
			&i.EntityDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, entity_type, occurred_at, published_at
FROM entity_events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadType string             `json:"payload_type"`
	Payload     json.RawMessage    `json:"payload"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RelationKey pgtype.Text        `json:"relation_key"`
	Tags        []string           `json:"tags"`
	EntityType  string             `json:"entity_type"`
	OccurredAt  time.Time          `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.PayloadType,
		&i.Payload,
		&i.EntityID,
		&i.RelationKey,
		&i.Tags,
		&i.EntityType,
		&i.OccurredAt,
		&i.PublishedAt,
	)
	return i, err
}

const getEventsForEntity = `-- name: GetEventsForEntity :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, entity_type, occurred_at, published_at
FROM entity_events
WHERE entity_id = $1
  AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
  AND ($3::timestamptz = '0001-01-01' OR occurred_at > $3)
ORDER BY occurred_at DESC
LIMIT $4
`

type GetEventsForEntityParams struct {
	EntityID   pgtype.UUID `json:"entity_id"`
	EventTypes []string    `json:"event_types"`
	Since      time.Time   `json:"since"`
	MaxResults int32       `json:"max_results"`
}

type GetEventsForEntityRow struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadType string             `json:"payload_type"`
	Payload     json.RawMessage    `json:"payload"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RelationKey pgtype.Text        `json:"relation_key"`
	Tags        []string           `json:"tags"`
	EntityType  string             `json:"entity_type"`
	OccurredAt  time.Time          `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetEventsForEntity(ctx context.Context, arg GetEventsForEntityParams) ([]GetEventsForEntityRow, error) {
	rows, err := q.db.Query(ctx, getEventsForEntity,
		arg.EntityID,
		arg.EventTypes,
		arg.Since,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsForEntityRow
	for rows.Next() {
		var i GetEventsForEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.EntityType,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastEventTime = `-- name: GetLastEventTime :one
SELECT occurred_at FROM entity_events ORDER BY occurred_at DESC LIMIT 1
`

func (q *Queries) GetLastEventTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLastEventTime)
	var occurred_at time.Time
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO entity_events (id, event_type, payload_type, payload, entity_id, relation_key, tags, entity_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEventParams struct {
	ID          uuid.UUID       `json:"id"`
	EventType   string          `json:"event_type"`
	PayloadType string          `json:"payload_type"`
	Payload     json.RawMessage `json:"payload"`
	EntityID    pgtype.UUID     `json:"entity_id"`
	RelationKey pgtype.Text     `json:"relation_key"`
	Tags        []string        `json:"tags"`
	EntityType  string          `json:"entity_type"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.PayloadType,
		arg.Payload,
		arg.EntityID,
		arg.RelationKey,
		arg.Tags,
		arg.EntityType,
	)
	return err
}
