// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnpublishedEvents = `-- name: CountUnpublishedEvents :one
SELECT count(*) FROM entity_events WHERE published_at IS NULL
`

func (q *Queries) CountUnpublishedEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublishedEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, occurred_at, published_at
FROM entity_events
WHERE (cardinality($1::text[]) = 0 OR event_type = ANY($1))
  AND ($2::timestamptz IS NULL OR occurred_at < $2::timestamptz)
ORDER BY occurred_at DESC
LIMIT $3
`

type GetAllEventsParams struct {
	EventTypes []string           `json:"event_types"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	MaxResults int32              `json:"max_results"`
}

func (q *Queries) GetAllEvents(ctx context.Context, arg GetAllEventsParams) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getAllEvents, arg.EventTypes, arg.Cursor, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForEntity = `-- name: GetEventsForEntity :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, occurred_at, published_at
FROM entity_events
WHERE entity_id = $1
  AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
  AND ($3::timestamptz = '0001-01-01' OR occurred_at > $3)
ORDER BY occurred_at DESC
LIMIT $4
`

type GetEventsForEntityParams struct {
	EntityID   pgtype.UUID `json:"entity_id"`
	EventTypes []string    `json:"event_types"`
	Since      time.Time   `json:"since"`
	MaxResults int32       `json:"max_results"`
}

func (q *Queries) GetEventsForEntity(ctx context.Context, arg GetEventsForEntityParams) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForEntity,
		arg.EntityID,
		arg.EventTypes,
		arg.Since,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastEventTime = `-- name: GetLastEventTime :one
SELECT occurred_at FROM entity_events ORDER BY occurred_at DESC LIMIT 1
`

func (q *Queries) GetLastEventTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLastEventTime)
	var occurred_at time.Time
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const getLastPublishedTime = `-- name: GetLastPublishedTime :one
SELECT published_at FROM entity_events WHERE published_at IS NOT NULL ORDER BY published_at DESC LIMIT 1
`

func (q *Queries) GetLastPublishedTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastPublishedTime)
	var published_at pgtype.Timestamptz
	err := row.Scan(&published_at)
	return published_at, err
}

const getPublisherLock = `-- name: GetPublisherLock :one
SELECT holder_id, acquired_at, expires_at, renewed_at FROM publisher_lock WHERE id = 'singleton'
`

type GetPublisherLockRow struct {
	HolderID   string    `json:"holder_id"`
	AcquiredAt time.Time `json:"acquired_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	RenewedAt  time.Time `json:"renewed_at"`
}

func (q *Queries) GetPublisherLock(ctx context.Context) (GetPublisherLockRow, error) {
	row := q.db.QueryRow(ctx, getPublisherLock)
	var i GetPublisherLockRow
	err := row.Scan(
		&i.HolderID,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.RenewedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO entity_events (id, event_type, payload_type, payload, entity_id, relation_key, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID          uuid.UUID       `json:"id"`
	EventType   string          `json:"event_type"`
	PayloadType string          `json:"payload_type"`
	Payload     json.RawMessage `json:"payload"`
	EntityID    pgtype.UUID     `json:"entity_id"`
	RelationKey pgtype.Text     `json:"relation_key"`
	Tags        []string        `json:"tags"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.PayloadType,
		arg.Payload,
		arg.EntityID,
		arg.RelationKey,
		arg.Tags,
	)
	return err
}
