// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEventsForJob = `-- name: GetEventsForJob :many
SELECT id, job_id, entity_id, event_type, entity_type, local_entity_id, data, published_at, created_at
FROM entity_events
WHERE job_id = $1
ORDER BY created_at
`

func (q *Queries) GetEventsForJob(ctx context.Context, jobID uuid.UUID) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EntityID,
			&i.EventType,
			&i.EntityType,
			&i.LocalEntityID,
			&i.Data,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, job_id, entity_id, event_type, entity_type, local_entity_id, data, published_at, created_at
FROM entity_events
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context, limit int32) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EntityID,
			&i.EventType,
			&i.EntityType,
			&i.LocalEntityID,
			&i.Data,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO entity_events (job_id, entity_id, event_type, entity_type, local_entity_id, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, entity_id, event_type, entity_type, local_entity_id, data, published_at, created_at
`

type InsertEventParams struct {
	JobID         uuid.UUID       `json:"job_id"`
	EntityID      pgtype.UUID     `json:"entity_id"`
	EventType     string          `json:"event_type"`
	EntityType    string          `json:"entity_type"`
	LocalEntityID string          `json:"local_entity_id"`
	Data          json.RawMessage `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (EntityEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.JobID,
		arg.EntityID,
		arg.EventType,
		arg.EntityType,
		arg.LocalEntityID,
		arg.Data,
	)
	var i EntityEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.EntityID,
		&i.EventType,
		&i.EntityType,
		&i.LocalEntityID,
		&i.Data,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEventsPublished = `-- name: MarkEventsPublished :exec
UPDATE entity_events
SET published_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkEventsPublished(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markEventsPublished, dollar_1)
	return err
}
