// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getJobSteps = `-- name: GetJobSteps :many
SELECT id, job_id, step_name, step_order, status, error_msg, started_at, completed_at
FROM job_steps
WHERE job_id = $1
ORDER BY step_order
`

func (q *Queries) GetJobSteps(ctx context.Context, jobID uuid.UUID) ([]JobStep, error) {
	rows, err := q.db.Query(ctx, getJobSteps, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobStep
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StepName,
			&i.StepOrder,
			&i.Status,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJobStep = `-- name: InsertJobStep :one
INSERT INTO job_steps (job_id, step_name, step_order)
VALUES ($1, $2, $3)
RETURNING id, job_id, step_name, step_order, status, error_msg, started_at, completed_at
`

type InsertJobStepParams struct {
	JobID     uuid.UUID `json:"job_id"`
	StepName  string    `json:"step_name"`
	StepOrder int32     `json:"step_order"`
}

func (q *Queries) InsertJobStep(ctx context.Context, arg InsertJobStepParams) (JobStep, error) {
	row := q.db.QueryRow(ctx, insertJobStep, arg.JobID, arg.StepName, arg.StepOrder)
	var i JobStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StepName,
		&i.StepOrder,
		&i.Status,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJobStepStatus = `-- name: UpdateJobStepStatus :exec
UPDATE job_steps
SET status = $2,
    error_msg = $3,
    started_at = CASE WHEN $2 = 'processing' AND started_at IS NULL THEN now() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'skipped') THEN now() ELSE completed_at END
WHERE id = $1
`

type UpdateJobStepStatusParams struct {
	ID       uuid.UUID   `json:"id"`
	Status   string      `json:"status"`
	ErrorMsg pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateJobStepStatus(ctx context.Context, arg UpdateJobStepStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStepStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}
