// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Entity struct {
	ID         uuid.UUID          `json:"id"`
	EntityType string             `json:"entity_type"`
	Data       json.RawMessage    `json:"data"`
	Confidence float64            `json:"confidence"`
	Tags       []string           `json:"tags"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type EntityAnchor struct {
	EntityID        uuid.UUID `json:"entity_id"`
	EntityType      string    `json:"entity_type"`
	AnchorField     string    `json:"anchor_field"`
	NormalizedValue string    `json:"normalized_value"`
}

type EntityProvenance struct {
	ID              uuid.UUID `json:"id"`
	EntityID        uuid.UUID `json:"entity_id"`
	SourceUrn       string    `json:"source_urn"`
	ExtractedAt     time.Time `json:"extracted_at"`
	ModelID         string    `json:"model_id"`
	Confidence      float64   `json:"confidence"`
	Fields          []string  `json:"fields"`
	MatchMethod     string    `json:"match_method"`
	MatchConfidence float64   `json:"match_confidence"`
}

type EntityRelation struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

type EntityToken struct {
	EntityID   uuid.UUID `json:"entity_id"`
	EntityType string    `json:"entity_type"`
	TokenField string    `json:"token_field"`
	Tokens     []string  `json:"tokens"`
}
