// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Entity struct {
	ID          uuid.UUID          `json:"id"`
	EntityType  string             `json:"entity_type"`
	Data        json.RawMessage    `json:"data"`
	Confidence  float64            `json:"confidence"`
	Tags        []string           `json:"tags"`
	Embedding   pgvector_go.Vector `json:"embedding"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DisplayName string             `json:"display_name"`
	Version     int32              `json:"version"`
}

type EntityAnchor struct {
	EntityID        uuid.UUID `json:"entity_id"`
	EntityType      string    `json:"entity_type"`
	AnchorField     string    `json:"anchor_field"`
	NormalizedValue string    `json:"normalized_value"`
}

type EntityEvent struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadType string             `json:"payload_type"`
	Payload     json.RawMessage    `json:"payload"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RelationKey pgtype.Text        `json:"relation_key"`
	Tags        []string           `json:"tags"`
	OccurredAt  time.Time          `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type EntityEventConsumer struct {
	Name                string             `json:"name"`
	LastEventAt         time.Time          `json:"last_event_at"`
	LastEventID         pgtype.UUID        `json:"last_event_id"`
	HolderID            pgtype.Text        `json:"holder_id"`
	AcquiredAt          pgtype.Timestamptz `json:"acquired_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	BackoffUntil        pgtype.Timestamptz `json:"backoff_until"`
}

type EntityEventDeadLetter struct {
	ID           int64       `json:"id"`
	ConsumerName string      `json:"consumer_name"`
	EventID      uuid.UUID   `json:"event_id"`
	EventType    string      `json:"event_type"`
	PayloadType  string      `json:"payload_type"`
	EntityID     pgtype.Text `json:"entity_id"`
	Payload      []byte      `json:"payload"`
	ErrorMessage string      `json:"error_message"`
	RetryCount   int32       `json:"retry_count"`
	CreatedAt    time.Time   `json:"created_at"`
}

type EntityEventsDefault struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadType string             `json:"payload_type"`
	Payload     json.RawMessage    `json:"payload"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RelationKey pgtype.Text        `json:"relation_key"`
	Tags        []string           `json:"tags"`
	OccurredAt  time.Time          `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type EntityRelation struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
	DataType     string          `json:"data_type"`
}

type EntityToken struct {
	EntityID   uuid.UUID `json:"entity_id"`
	EntityType string    `json:"entity_type"`
	TokenField string    `json:"token_field"`
	Tokens     []string  `json:"tokens"`
}
