// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provenance.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteProvenanceForEntity = `-- name: DeleteProvenanceForEntity :exec
DELETE FROM entity_provenance WHERE entity_id = $1
`

func (q *Queries) DeleteProvenanceForEntity(ctx context.Context, entityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvenanceForEntity, entityID)
	return err
}

const getProvenanceForEntity = `-- name: GetProvenanceForEntity :many
SELECT id, entity_id, source_urn, extracted_at, model_id, confidence, fields, match_method, match_confidence
FROM entity_provenance
WHERE entity_id = $1
ORDER BY extracted_at DESC
`

func (q *Queries) GetProvenanceForEntity(ctx context.Context, entityID uuid.UUID) ([]EntityProvenance, error) {
	rows, err := q.db.Query(ctx, getProvenanceForEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityProvenance
	for rows.Next() {
		var i EntityProvenance
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.SourceUrn,
			&i.ExtractedAt,
			&i.ModelID,
			&i.Confidence,
			&i.Fields,
			&i.MatchMethod,
			&i.MatchConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvenanceForSource = `-- name: GetProvenanceForSource :many
SELECT id, entity_id, source_urn, extracted_at, model_id, confidence, fields, match_method, match_confidence
FROM entity_provenance
WHERE source_urn = $1
ORDER BY extracted_at DESC
`

func (q *Queries) GetProvenanceForSource(ctx context.Context, sourceUrn string) ([]EntityProvenance, error) {
	rows, err := q.db.Query(ctx, getProvenanceForSource, sourceUrn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityProvenance
	for rows.Next() {
		var i EntityProvenance
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.SourceUrn,
			&i.ExtractedAt,
			&i.ModelID,
			&i.Confidence,
			&i.Fields,
			&i.MatchMethod,
			&i.MatchConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProvenance = `-- name: InsertProvenance :one
INSERT INTO entity_provenance (entity_id, source_urn, extracted_at, model_id, confidence, fields, match_method, match_confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, entity_id, source_urn, extracted_at, model_id, confidence, fields, match_method, match_confidence
`

type InsertProvenanceParams struct {
	EntityID        uuid.UUID `json:"entity_id"`
	SourceUrn       string    `json:"source_urn"`
	ExtractedAt     time.Time `json:"extracted_at"`
	ModelID         string    `json:"model_id"`
	Confidence      float64   `json:"confidence"`
	Fields          []string  `json:"fields"`
	MatchMethod     string    `json:"match_method"`
	MatchConfidence float64   `json:"match_confidence"`
}

func (q *Queries) InsertProvenance(ctx context.Context, arg InsertProvenanceParams) (EntityProvenance, error) {
	row := q.db.QueryRow(ctx, insertProvenance,
		arg.EntityID,
		arg.SourceUrn,
		arg.ExtractedAt,
		arg.ModelID,
		arg.Confidence,
		arg.Fields,
		arg.MatchMethod,
		arg.MatchConfidence,
	)
	var i EntityProvenance
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.SourceUrn,
		&i.ExtractedAt,
		&i.ModelID,
		&i.Confidence,
		&i.Fields,
		&i.MatchMethod,
		&i.MatchConfidence,
	)
	return i, err
}
