// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, event_type, payload_type, payload, entity_id, relation_key, tags, occurred_at, published_at
FROM entity_events
WHERE published_at IS NULL
ORDER BY occurred_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context, batchSize int32) ([]EntityEvent, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityEvent
	for rows.Next() {
		var i EntityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PayloadType,
			&i.Payload,
			&i.EntityID,
			&i.RelationKey,
			&i.Tags,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsPublished = `-- name: MarkEventsPublished :exec
UPDATE entity_events
SET published_at = now()
WHERE id = ANY($1::uuid[])
  AND occurred_at = ANY($2::timestamptz[])
`

type MarkEventsPublishedParams struct {
	Ids         []uuid.UUID `json:"ids"`
	OccurredAts []time.Time `json:"occurred_ats"`
}

func (q *Queries) MarkEventsPublished(ctx context.Context, arg MarkEventsPublishedParams) error {
	_, err := q.db.Exec(ctx, markEventsPublished, arg.Ids, arg.OccurredAts)
	return err
}

const releaseLock = `-- name: ReleaseLock :exec
DELETE FROM publisher_lock WHERE holder_id = $1
`

func (q *Queries) ReleaseLock(ctx context.Context, holderID string) error {
	_, err := q.db.Exec(ctx, releaseLock, holderID)
	return err
}

const renewLock = `-- name: RenewLock :execresult
UPDATE publisher_lock
SET expires_at = now() + $1::interval, renewed_at = now()
WHERE holder_id = $2
`

type RenewLockParams struct {
	Ttl      pgtype.Interval `json:"ttl"`
	HolderID string          `json:"holder_id"`
}

func (q *Queries) RenewLock(ctx context.Context, arg RenewLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, renewLock, arg.Ttl, arg.HolderID)
}

const tryAcquireLock = `-- name: TryAcquireLock :execresult
INSERT INTO publisher_lock (holder_id, expires_at, renewed_at)
VALUES ($1, now() + $2::interval, now())
ON CONFLICT (id) DO UPDATE
SET holder_id = EXCLUDED.holder_id,
    acquired_at = now(),
    expires_at = EXCLUDED.expires_at,
    renewed_at = now()
WHERE publisher_lock.expires_at < now()
`

type TryAcquireLockParams struct {
	HolderID string          `json:"holder_id"`
	Ttl      pgtype.Interval `json:"ttl"`
}

func (q *Queries) TryAcquireLock(ctx context.Context, arg TryAcquireLockParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, tryAcquireLock, arg.HolderID, arg.Ttl)
}
