// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relations.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const connectedEntities = `-- name: ConnectedEntities :many
SELECT DISTINCT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM (
    SELECT r.target_id AS connected_id FROM entity_relations r WHERE r.source_id = $1
    UNION
    SELECT r.source_id AS connected_id FROM entity_relations r WHERE r.target_id = $1
) AS conns
JOIN entities e ON e.id = conns.connected_id
WHERE e.deleted_at IS NULL
LIMIT $2
`

type ConnectedEntitiesParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	PageSize int32     `json:"page_size"`
}

type ConnectedEntitiesRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) ConnectedEntities(ctx context.Context, arg ConnectedEntitiesParams) ([]ConnectedEntitiesRow, error) {
	rows, err := q.db.Query(ctx, connectedEntities, arg.EntityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedEntitiesRow
	for rows.Next() {
		var i ConnectedEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM entity_relations WHERE id = $1
`

func (q *Queries) DeleteRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelation, id)
	return err
}

const deleteRelationByKey = `-- name: DeleteRelationByKey :exec
DELETE FROM entity_relations
WHERE source_id = $1
  AND target_id = $2
  AND relation_type = $3
`

type DeleteRelationByKeyParams struct {
	SourceID     uuid.UUID `json:"source_id"`
	TargetID     uuid.UUID `json:"target_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) DeleteRelationByKey(ctx context.Context, arg DeleteRelationByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteRelationByKey, arg.SourceID, arg.TargetID, arg.RelationType)
	return err
}

const deleteRelationsForEntity = `-- name: DeleteRelationsForEntity :exec
DELETE FROM entity_relations WHERE source_id = $1 OR target_id = $1
`

func (q *Queries) DeleteRelationsForEntity(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelationsForEntity, sourceID)
	return err
}

const findConnectedByTypeInbound = `-- name: FindConnectedByTypeInbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id
WHERE r.target_id = $1
  AND e.deleted_at IS NULL
  AND ($2::text = '' OR e.entity_type = $2::text)
  AND (cardinality($3::text[]) = 0 OR r.relation_type = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
  AND (cardinality($5::text[]) = 0 OR e.tags && $5::text[])
  AND ($6 = '' OR NOT ($6 = ANY(e.tags)) OR e.tags && $7::text[])
  AND ($8::timestamptz IS NULL OR r.created_at < $8::timestamptz)
ORDER BY r.created_at DESC
LIMIT $9
`

type FindConnectedByTypeInboundParams struct {
	EntityID      uuid.UUID          `json:"entity_id"`
	EntityType    string             `json:"entity_type"`
	RelationTypes []string           `json:"relation_types"`
	Tags          []string           `json:"tags"`
	AnyTags       []string           `json:"any_tags"`
	ExcludeTag    interface{}        `json:"exclude_tag"`
	UnlessTags    []string           `json:"unless_tags"`
	Cursor        pgtype.Timestamptz `json:"cursor"`
	PageSize      int32              `json:"page_size"`
}

type FindConnectedByTypeInboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindConnectedByTypeInbound(ctx context.Context, arg FindConnectedByTypeInboundParams) ([]FindConnectedByTypeInboundRow, error) {
	rows, err := q.db.Query(ctx, findConnectedByTypeInbound,
		arg.EntityID,
		arg.EntityType,
		arg.RelationTypes,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConnectedByTypeInboundRow
	for rows.Next() {
		var i FindConnectedByTypeInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConnectedByTypeOutbound = `-- name: FindConnectedByTypeOutbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.target_id
WHERE r.source_id = $1
  AND e.deleted_at IS NULL
  AND ($2::text = '' OR e.entity_type = $2::text)
  AND (cardinality($3::text[]) = 0 OR r.relation_type = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
  AND (cardinality($5::text[]) = 0 OR e.tags && $5::text[])
  AND ($6 = '' OR NOT ($6 = ANY(e.tags)) OR e.tags && $7::text[])
  AND ($8::timestamptz IS NULL OR r.created_at < $8::timestamptz)
ORDER BY r.created_at DESC
LIMIT $9
`

type FindConnectedByTypeOutboundParams struct {
	EntityID      uuid.UUID          `json:"entity_id"`
	EntityType    string             `json:"entity_type"`
	RelationTypes []string           `json:"relation_types"`
	Tags          []string           `json:"tags"`
	AnyTags       []string           `json:"any_tags"`
	ExcludeTag    interface{}        `json:"exclude_tag"`
	UnlessTags    []string           `json:"unless_tags"`
	Cursor        pgtype.Timestamptz `json:"cursor"`
	PageSize      int32              `json:"page_size"`
}

type FindConnectedByTypeOutboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindConnectedByTypeOutbound(ctx context.Context, arg FindConnectedByTypeOutboundParams) ([]FindConnectedByTypeOutboundRow, error) {
	rows, err := q.db.Query(ctx, findConnectedByTypeOutbound,
		arg.EntityID,
		arg.EntityType,
		arg.RelationTypes,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConnectedByTypeOutboundRow
	for rows.Next() {
		var i FindConnectedByTypeOutboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesByRelationSource = `-- name: FindEntitiesByRelationSource :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id
WHERE e.entity_type = $1
  AND e.deleted_at IS NULL
  AND r.relation_type = $2
  AND (cardinality($3::text[]) = 0 OR e.tags @> $3::text[])
  AND (cardinality($4::text[]) = 0 OR e.tags && $4::text[])
  AND ($5::text = '' OR NOT ($5::text = ANY(e.tags)) OR e.tags && $6::text[])
`

type FindEntitiesByRelationSourceParams struct {
	EntityType   string   `json:"entity_type"`
	RelationType string   `json:"relation_type"`
	Tags         []string `json:"tags"`
	AnyTags      []string `json:"any_tags"`
	ExcludeTag   string   `json:"exclude_tag"`
	UnlessTags   []string `json:"unless_tags"`
}

type FindEntitiesByRelationSourceRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindEntitiesByRelationSource(ctx context.Context, arg FindEntitiesByRelationSourceParams) ([]FindEntitiesByRelationSourceRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByRelationSource,
		arg.EntityType,
		arg.RelationType,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEntitiesByRelationSourceRow
	for rows.Next() {
		var i FindEntitiesByRelationSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesByRelationTarget = `-- name: FindEntitiesByRelationTarget :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.target_id
WHERE e.entity_type = $1
  AND e.deleted_at IS NULL
  AND r.relation_type = $2
  AND (cardinality($3::text[]) = 0 OR e.tags @> $3::text[])
  AND (cardinality($4::text[]) = 0 OR e.tags && $4::text[])
  AND ($5::text = '' OR NOT ($5::text = ANY(e.tags)) OR e.tags && $6::text[])
`

type FindEntitiesByRelationTargetParams struct {
	EntityType   string   `json:"entity_type"`
	RelationType string   `json:"relation_type"`
	Tags         []string `json:"tags"`
	AnyTags      []string `json:"any_tags"`
	ExcludeTag   string   `json:"exclude_tag"`
	UnlessTags   []string `json:"unless_tags"`
}

type FindEntitiesByRelationTargetRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindEntitiesByRelationTarget(ctx context.Context, arg FindEntitiesByRelationTargetParams) ([]FindEntitiesByRelationTargetRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByRelationTarget,
		arg.EntityType,
		arg.RelationType,
		arg.Tags,
		arg.AnyTags,
		arg.ExcludeTag,
		arg.UnlessTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEntitiesByRelationTargetRow
	for rows.Next() {
		var i FindEntitiesByRelationTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsByType = `-- name: GetRelationsByType :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
FROM entity_relations
WHERE relation_type = $1
ORDER BY created_at DESC
`

type GetRelationsByTypeRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetRelationsByType(ctx context.Context, relationType string) ([]GetRelationsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getRelationsByType, relationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelationsByTypeRow
	for rows.Next() {
		var i GetRelationsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.DataType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsForSource = `-- name: GetRelationsForSource :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
FROM entity_relations
WHERE source_urn = $1
ORDER BY created_at DESC
`

type GetRelationsForSourceRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetRelationsForSource(ctx context.Context, sourceUrn pgtype.Text) ([]GetRelationsForSourceRow, error) {
	rows, err := q.db.Query(ctx, getRelationsForSource, sourceUrn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelationsForSourceRow
	for rows.Next() {
		var i GetRelationsForSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.DataType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsFromEntity = `-- name: GetRelationsFromEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
FROM entity_relations
WHERE source_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type GetRelationsFromEntityParams struct {
	SourceID uuid.UUID          `json:"source_id"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
	PageSize int32              `json:"page_size"`
}

type GetRelationsFromEntityRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetRelationsFromEntity(ctx context.Context, arg GetRelationsFromEntityParams) ([]GetRelationsFromEntityRow, error) {
	rows, err := q.db.Query(ctx, getRelationsFromEntity, arg.SourceID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelationsFromEntityRow
	for rows.Next() {
		var i GetRelationsFromEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.DataType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsToEntity = `-- name: GetRelationsToEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
FROM entity_relations
WHERE target_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type GetRelationsToEntityParams struct {
	TargetID uuid.UUID          `json:"target_id"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
	PageSize int32              `json:"page_size"`
}

type GetRelationsToEntityRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetRelationsToEntity(ctx context.Context, arg GetRelationsToEntityParams) ([]GetRelationsToEntityRow, error) {
	rows, err := q.db.Query(ctx, getRelationsToEntity, arg.TargetID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelationsToEntityRow
	for rows.Next() {
		var i GetRelationsToEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.DataType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationData = `-- name: UpdateRelationData :one
UPDATE entity_relations
SET data_type = $1, data = $2
WHERE source_id = $3
  AND target_id = $4
  AND relation_type = $5
RETURNING id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
`

type UpdateRelationDataParams struct {
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
}

type UpdateRelationDataRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) UpdateRelationData(ctx context.Context, arg UpdateRelationDataParams) (UpdateRelationDataRow, error) {
	row := q.db.QueryRow(ctx, updateRelationData,
		arg.DataType,
		arg.Data,
		arg.SourceID,
		arg.TargetID,
		arg.RelationType,
	)
	var i UpdateRelationDataRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Confidence,
		&i.Evidence,
		&i.Implied,
		&i.SourceUrn,
		&i.DataType,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO entity_relations (source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source_id, target_id, relation_type) WHERE source_urn IS NULL
DO UPDATE SET confidence = EXCLUDED.confidence, evidence = EXCLUDED.evidence, data_type = EXCLUDED.data_type, data = EXCLUDED.data
RETURNING id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data_type, data, created_at
`

type UpsertRelationParams struct {
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
}

type UpsertRelationRow struct {
	ID           uuid.UUID       `json:"id"`
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	DataType     string          `json:"data_type"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (UpsertRelationRow, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.SourceID,
		arg.TargetID,
		arg.RelationType,
		arg.Confidence,
		arg.Evidence,
		arg.Implied,
		arg.SourceUrn,
		arg.DataType,
		arg.Data,
	)
	var i UpsertRelationRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Confidence,
		&i.Evidence,
		&i.Implied,
		&i.SourceUrn,
		&i.DataType,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
