// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relations.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const connectedEntitiesInbound = `-- name: ConnectedEntitiesInbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id
WHERE r.target_id = $1
`

type ConnectedEntitiesInboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) ConnectedEntitiesInbound(ctx context.Context, targetID uuid.UUID) ([]ConnectedEntitiesInboundRow, error) {
	rows, err := q.db.Query(ctx, connectedEntitiesInbound, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedEntitiesInboundRow
	for rows.Next() {
		var i ConnectedEntitiesInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectedEntitiesOutbound = `-- name: ConnectedEntitiesOutbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.target_id
WHERE r.source_id = $1
`

type ConnectedEntitiesOutboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) ConnectedEntitiesOutbound(ctx context.Context, sourceID uuid.UUID) ([]ConnectedEntitiesOutboundRow, error) {
	rows, err := q.db.Query(ctx, connectedEntitiesOutbound, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedEntitiesOutboundRow
	for rows.Next() {
		var i ConnectedEntitiesOutboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM entity_relations WHERE id = $1
`

func (q *Queries) DeleteRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelation, id)
	return err
}

const deleteRelationsForEntity = `-- name: DeleteRelationsForEntity :exec
DELETE FROM entity_relations WHERE source_id = $1 OR target_id = $1
`

func (q *Queries) DeleteRelationsForEntity(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelationsForEntity, sourceID)
	return err
}

const findConnectedByTypeInbound = `-- name: FindConnectedByTypeInbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id
WHERE r.target_id = $1
  AND e.entity_type = $2
  AND (cardinality($3::text[]) = 0 OR r.relation_type = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
`

type FindConnectedByTypeInboundParams struct {
	EntityID      uuid.UUID `json:"entity_id"`
	EntityType    string    `json:"entity_type"`
	RelationTypes []string  `json:"relation_types"`
	Tags          []string  `json:"tags"`
}

type FindConnectedByTypeInboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindConnectedByTypeInbound(ctx context.Context, arg FindConnectedByTypeInboundParams) ([]FindConnectedByTypeInboundRow, error) {
	rows, err := q.db.Query(ctx, findConnectedByTypeInbound,
		arg.EntityID,
		arg.EntityType,
		arg.RelationTypes,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConnectedByTypeInboundRow
	for rows.Next() {
		var i FindConnectedByTypeInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConnectedByTypeOutbound = `-- name: FindConnectedByTypeOutbound :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.target_id
WHERE r.source_id = $1
  AND e.entity_type = $2
  AND (cardinality($3::text[]) = 0 OR r.relation_type = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
`

type FindConnectedByTypeOutboundParams struct {
	EntityID      uuid.UUID `json:"entity_id"`
	EntityType    string    `json:"entity_type"`
	RelationTypes []string  `json:"relation_types"`
	Tags          []string  `json:"tags"`
}

type FindConnectedByTypeOutboundRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindConnectedByTypeOutbound(ctx context.Context, arg FindConnectedByTypeOutboundParams) ([]FindConnectedByTypeOutboundRow, error) {
	rows, err := q.db.Query(ctx, findConnectedByTypeOutbound,
		arg.EntityID,
		arg.EntityType,
		arg.RelationTypes,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConnectedByTypeOutboundRow
	for rows.Next() {
		var i FindConnectedByTypeOutboundRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesByRelationSource = `-- name: FindEntitiesByRelationSource :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id
WHERE e.entity_type = $1
  AND r.relation_type = $2
  AND (cardinality($3::text[]) = 0 OR e.tags @> $3::text[])
`

type FindEntitiesByRelationSourceParams struct {
	EntityType   string   `json:"entity_type"`
	RelationType string   `json:"relation_type"`
	Tags         []string `json:"tags"`
}

type FindEntitiesByRelationSourceRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindEntitiesByRelationSource(ctx context.Context, arg FindEntitiesByRelationSourceParams) ([]FindEntitiesByRelationSourceRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByRelationSource, arg.EntityType, arg.RelationType, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEntitiesByRelationSourceRow
	for rows.Next() {
		var i FindEntitiesByRelationSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesByRelationTarget = `-- name: FindEntitiesByRelationTarget :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.target_id
WHERE e.entity_type = $1
  AND r.relation_type = $2
  AND (cardinality($3::text[]) = 0 OR e.tags @> $3::text[])
`

type FindEntitiesByRelationTargetParams struct {
	EntityType   string   `json:"entity_type"`
	RelationType string   `json:"relation_type"`
	Tags         []string `json:"tags"`
}

type FindEntitiesByRelationTargetRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindEntitiesByRelationTarget(ctx context.Context, arg FindEntitiesByRelationTargetParams) ([]FindEntitiesByRelationTargetRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByRelationTarget, arg.EntityType, arg.RelationType, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEntitiesByRelationTargetRow
	for rows.Next() {
		var i FindEntitiesByRelationTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsByType = `-- name: GetRelationsByType :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data, created_at
FROM entity_relations
WHERE relation_type = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsByType(ctx context.Context, relationType string) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsByType, relationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsForSource = `-- name: GetRelationsForSource :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data, created_at
FROM entity_relations
WHERE source_urn = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsForSource(ctx context.Context, sourceUrn pgtype.Text) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsForSource, sourceUrn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsFromEntity = `-- name: GetRelationsFromEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data, created_at
FROM entity_relations
WHERE source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsFromEntity(ctx context.Context, sourceID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsFromEntity, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsToEntity = `-- name: GetRelationsToEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data, created_at
FROM entity_relations
WHERE target_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsToEntity(ctx context.Context, targetID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsToEntity, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.SourceUrn,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO entity_relations (source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_id, target_id, relation_type) WHERE source_urn IS NULL
DO UPDATE SET confidence = EXCLUDED.confidence, evidence = EXCLUDED.evidence, data = entity_relations.data || EXCLUDED.data
RETURNING id, source_id, target_id, relation_type, confidence, evidence, implied, source_urn, data, created_at
`

type UpsertRelationParams struct {
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	SourceUrn    pgtype.Text     `json:"source_urn"`
	Data         json.RawMessage `json:"data"`
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.SourceID,
		arg.TargetID,
		arg.RelationType,
		arg.Confidence,
		arg.Evidence,
		arg.Implied,
		arg.SourceUrn,
		arg.Data,
	)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Confidence,
		&i.Evidence,
		&i.Implied,
		&i.SourceUrn,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
