// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relations.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const connectedEntities = `-- name: ConnectedEntities :many
SELECT DISTINCT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = CASE WHEN r.source_id = $1 THEN r.target_id ELSE r.source_id END
WHERE r.source_id = $1 OR r.target_id = $1
`

type ConnectedEntitiesRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) ConnectedEntities(ctx context.Context, sourceID uuid.UUID) ([]ConnectedEntitiesRow, error) {
	rows, err := q.db.Query(ctx, connectedEntities, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedEntitiesRow
	for rows.Next() {
		var i ConnectedEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM entity_relations WHERE id = $1
`

func (q *Queries) DeleteRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelation, id)
	return err
}

const deleteRelationsForEntity = `-- name: DeleteRelationsForEntity :exec
DELETE FROM entity_relations WHERE source_id = $1 OR target_id = $1
`

func (q *Queries) DeleteRelationsForEntity(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelationsForEntity, sourceID)
	return err
}

const findConnectedByType = `-- name: FindConnectedByType :many
SELECT DISTINCT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = CASE WHEN r.source_id = $1 THEN r.target_id ELSE r.source_id END
WHERE (r.source_id = $1 OR r.target_id = $1)
  AND e.entity_type = $2
  AND (cardinality($3::text[]) = 0 OR r.relation_type = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
ORDER BY e.updated_at DESC
`

type FindConnectedByTypeParams struct {
	EntityID      uuid.UUID `json:"entity_id"`
	EntityType    string    `json:"entity_type"`
	RelationTypes []string  `json:"relation_types"`
	Tags          []string  `json:"tags"`
}

type FindConnectedByTypeRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindConnectedByType(ctx context.Context, arg FindConnectedByTypeParams) ([]FindConnectedByTypeRow, error) {
	rows, err := q.db.Query(ctx, findConnectedByType,
		arg.EntityID,
		arg.EntityType,
		arg.RelationTypes,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConnectedByTypeRow
	for rows.Next() {
		var i FindConnectedByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesByRelation = `-- name: FindEntitiesByRelation :many
SELECT DISTINCT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_relations r
JOIN entities e ON e.id = r.source_id OR e.id = r.target_id
WHERE e.entity_type = $1
  AND r.relation_type = $2
  AND (cardinality($3::text[]) = 0 OR e.tags @> $3::text[])
ORDER BY e.updated_at DESC
`

type FindEntitiesByRelationParams struct {
	EntityType   string   `json:"entity_type"`
	RelationType string   `json:"relation_type"`
	Tags         []string `json:"tags"`
}

type FindEntitiesByRelationRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindEntitiesByRelation(ctx context.Context, arg FindEntitiesByRelationParams) ([]FindEntitiesByRelationRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByRelation, arg.EntityType, arg.RelationType, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEntitiesByRelationRow
	for rows.Next() {
		var i FindEntitiesByRelationRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsByType = `-- name: GetRelationsByType :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, document_id, data, created_at
FROM entity_relations
WHERE relation_type = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsByType(ctx context.Context, relationType string) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsByType, relationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.DocumentID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsForDocument = `-- name: GetRelationsForDocument :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, document_id, data, created_at
FROM entity_relations
WHERE document_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsForDocument(ctx context.Context, documentID pgtype.Text) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.DocumentID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsFromEntity = `-- name: GetRelationsFromEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, document_id, data, created_at
FROM entity_relations
WHERE source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsFromEntity(ctx context.Context, sourceID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsFromEntity, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.DocumentID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsToEntity = `-- name: GetRelationsToEntity :many
SELECT id, source_id, target_id, relation_type, confidence, evidence, implied, document_id, data, created_at
FROM entity_relations
WHERE target_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRelationsToEntity(ctx context.Context, targetID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsToEntity, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelation
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Confidence,
			&i.Evidence,
			&i.Implied,
			&i.DocumentID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO entity_relations (source_id, target_id, relation_type, confidence, evidence, implied, document_id, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_id, target_id, relation_type) WHERE document_id IS NULL
DO UPDATE SET confidence = EXCLUDED.confidence, evidence = EXCLUDED.evidence, data = entity_relations.data || EXCLUDED.data
RETURNING id, source_id, target_id, relation_type, confidence, evidence, implied, document_id, data, created_at
`

type UpsertRelationParams struct {
	SourceID     uuid.UUID       `json:"source_id"`
	TargetID     uuid.UUID       `json:"target_id"`
	RelationType string          `json:"relation_type"`
	Confidence   float64         `json:"confidence"`
	Evidence     pgtype.Text     `json:"evidence"`
	Implied      bool            `json:"implied"`
	DocumentID   pgtype.Text     `json:"document_id"`
	Data         json.RawMessage `json:"data"`
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.SourceID,
		arg.TargetID,
		arg.RelationType,
		arg.Confidence,
		arg.Evidence,
		arg.Implied,
		arg.DocumentID,
		arg.Data,
	)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Confidence,
		&i.Evidence,
		&i.Implied,
		&i.DocumentID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
