// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tags.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const addEntityTags = `-- name: AddEntityTags :exec
UPDATE entities
SET tags = (
    SELECT ARRAY(SELECT DISTINCT unnest(tags || $1::text[]))
), updated_at = now()
WHERE id = $2
`

type AddEntityTagsParams struct {
	Tags     []string  `json:"tags"`
	EntityID uuid.UUID `json:"entity_id"`
}

func (q *Queries) AddEntityTags(ctx context.Context, arg AddEntityTagsParams) error {
	_, err := q.db.Exec(ctx, addEntityTags, arg.Tags, arg.EntityID)
	return err
}

const removeEntityTag = `-- name: RemoveEntityTag :exec
UPDATE entities
SET tags = array_remove(tags, $1), updated_at = now()
WHERE id = $2
`

type RemoveEntityTagParams struct {
	Tag      interface{} `json:"tag"`
	EntityID uuid.UUID   `json:"entity_id"`
}

func (q *Queries) RemoveEntityTag(ctx context.Context, arg RemoveEntityTagParams) error {
	_, err := q.db.Exec(ctx, removeEntityTag, arg.Tag, arg.EntityID)
	return err
}

const setEntityTags = `-- name: SetEntityTags :exec
UPDATE entities
SET tags = $1::text[], updated_at = now()
WHERE id = $2
`

type SetEntityTagsParams struct {
	Tags     []string  `json:"tags"`
	EntityID uuid.UUID `json:"entity_id"`
}

func (q *Queries) SetEntityTags(ctx context.Context, arg SetEntityTagsParams) error {
	_, err := q.db.Exec(ctx, setEntityTags, arg.Tags, arg.EntityID)
	return err
}
