// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteTokensForEntity = `-- name: DeleteTokensForEntity :exec
DELETE FROM entity_tokens WHERE entity_id = $1
`

func (q *Queries) DeleteTokensForEntity(ctx context.Context, entityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTokensForEntity, entityID)
	return err
}

const findByTokenOverlap = `-- name: FindByTokenOverlap :many
SELECT e.id, e.entity_type, e.data, e.confidence, e.tags, e.created_at, e.updated_at
FROM entity_tokens t
JOIN entities e ON e.id = t.entity_id
WHERE t.entity_type = $1 AND t.tokens && $2::text[]
  AND (cardinality($4::text[]) = 0 OR e.tags @> $4::text[])
ORDER BY array_length(
    ARRAY(SELECT unnest(t.tokens) INTERSECT SELECT unnest($2::text[])),
    1
) DESC NULLS LAST
LIMIT $3
`

type FindByTokenOverlapParams struct {
	EntityType string   `json:"entity_type"`
	Column2    []string `json:"column_2"`
	Limit      int32    `json:"limit"`
	Tags       []string `json:"tags"`
}

type FindByTokenOverlapRow struct {
	ID         uuid.UUID       `json:"id"`
	EntityType string          `json:"entity_type"`
	Data       json.RawMessage `json:"data"`
	Confidence float64         `json:"confidence"`
	Tags       []string        `json:"tags"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

func (q *Queries) FindByTokenOverlap(ctx context.Context, arg FindByTokenOverlapParams) ([]FindByTokenOverlapRow, error) {
	rows, err := q.db.Query(ctx, findByTokenOverlap,
		arg.EntityType,
		arg.Column2,
		arg.Limit,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByTokenOverlapRow
	for rows.Next() {
		var i FindByTokenOverlapRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Data,
			&i.Confidence,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTokens = `-- name: UpsertTokens :exec
INSERT INTO entity_tokens (entity_id, entity_type, token_field, tokens)
VALUES ($1, $2, $3, $4)
ON CONFLICT (entity_id, token_field) DO UPDATE
SET tokens = EXCLUDED.tokens
`

type UpsertTokensParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	EntityType string    `json:"entity_type"`
	TokenField string    `json:"token_field"`
	Tokens     []string  `json:"tokens"`
}

func (q *Queries) UpsertTokens(ctx context.Context, arg UpsertTokensParams) error {
	_, err := q.db.Exec(ctx, upsertTokens,
		arg.EntityID,
		arg.EntityType,
		arg.TokenField,
		arg.Tokens,
	)
	return err
}
