// Command protoc-gen-entitystore is a protoc/buf plugin that reads
// entitystore.v1 field and message options and generates Go code that
// returns a matching.EntityMatchConfig for each annotated message.
package main

import (
	"fmt"
	"strings"

	entitystorev1 "github.com/laenen-partners/entitystore/gen/entitystore/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	pluginpb "google.golang.org/protobuf/types/pluginpb"
)

const matchingPkg = "github.com/laenen-partners/entitystore/matching"
const extractionPkg = "github.com/laenen-partners/entitystore/extraction"
const storePkg = "github.com/laenen-partners/entitystore/store"

func ident(name string) protogen.GoIdent {
	return protogen.GoIdent{
		GoName:       name,
		GoImportPath: protogen.GoImportPath(matchingPkg),
	}
}

func extractionIdent(name string) protogen.GoIdent {
	return protogen.GoIdent{
		GoName:       name,
		GoImportPath: protogen.GoImportPath(extractionPkg),
	}
}

func storeIdent(name string) protogen.GoIdent {
	return protogen.GoIdent{
		GoName:       name,
		GoImportPath: protogen.GoImportPath(storePkg),
	}
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	var annotated []*protogen.Message
	for _, msg := range file.Messages {
		if hasAnnotations(msg) {
			annotated = append(annotated, msg)
		}
	}
	if len(annotated) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_entitystore.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-entitystore. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, msg := range annotated {
		generateMatchConfig(g, msg)
		generateExtractionSchema(g, msg)
		generateTokens(g, msg)
		generateEmbedText(g, msg)
		generateAnchors(g, msg)
		generateDisplayName(g, msg)
		generateWriteOp(g, msg)
	}

	return nil
}

func hasAnnotations(msg *protogen.Message) bool {
	if getMessageOptions(msg) != nil {
		return true
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field) != nil {
			return true
		}
	}
	return false
}

func getMessageOptions(msg *protogen.Message) *entitystorev1.MessageOptions {
	opts := msg.Desc.Options().(*descriptorpb.MessageOptions)
	if opts == nil {
		return nil
	}
	ext, ok := proto.GetExtension(opts, entitystorev1.E_Message).(*entitystorev1.MessageOptions)
	if !ok || ext == nil {
		return nil
	}
	return ext
}

func getFieldOptions(field *protogen.Field) *entitystorev1.FieldOptions {
	opts := field.Desc.Options().(*descriptorpb.FieldOptions)
	if opts == nil {
		return nil
	}
	ext, ok := proto.GetExtension(opts, entitystorev1.E_Field).(*entitystorev1.FieldOptions)
	if !ok || ext == nil {
		return nil
	}
	return ext
}

type fieldInfo struct {
	name string
	opts *entitystorev1.FieldOptions
}

// fieldInfoEx extends fieldInfo with the protogen field reference for getter generation.
type fieldInfoEx struct {
	fieldInfo
	field *protogen.Field
}

func generateMatchConfig(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName
	entityType := string(msg.Desc.FullName())

	var fields []fieldInfo
	for _, f := range msg.Fields {
		fo := getFieldOptions(f)
		if fo != nil {
			fields = append(fields, fieldInfo{
				name: string(f.Desc.Name()),
				opts: fo,
			})
		}
	}

	msgOpts := getMessageOptions(msg)

	g.P("// ", msgName, "MatchConfig returns the proto-annotation-derived matching")
	g.P("// configuration for ", entityType, ".")
	g.P("func ", msgName, "MatchConfig() ", ident("EntityMatchConfig"), " {")
	g.P("return ", ident("EntityMatchConfig"), "{")
	g.P("EntityType: ", fmt.Sprintf("%q", entityType), ",")

	// --- Anchors ---
	g.P("Anchors: ", ident("AnchorConfig"), "{")

	var singleAnchors []fieldInfo
	for _, fi := range fields {
		if fi.opts.Anchor {
			singleAnchors = append(singleAnchors, fi)
		}
	}
	if len(singleAnchors) > 0 {
		g.P("SingleAnchors: []", ident("AnchorField"), "{")
		for _, fi := range singleAnchors {
			g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fi.name), ", Normalizer: ", normalizerIdent(fi.opts.Normalizer), "},")
		}
		g.P("},")
	}

	if msgOpts != nil && len(msgOpts.CompositeAnchors) > 0 {
		g.P("CompositeAnchors: [][]", ident("AnchorField"), "{")
		for _, ca := range msgOpts.CompositeAnchors {
			g.P("{")
			for _, fieldName := range ca.Fields {
				norm := entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED
				for _, fi := range fields {
					if fi.name == fieldName {
						norm = fi.opts.Normalizer
						break
					}
				}
				g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fieldName), ", Normalizer: ", normalizerIdent(norm), "},")
			}
			g.P("},")
		}
		g.P("},")
	}
	g.P("},") // end Anchors

	// --- FieldWeights ---
	var weighted []fieldInfo
	for _, fi := range fields {
		if fi.opts.Weight > 0 {
			weighted = append(weighted, fi)
		}
	}
	if len(weighted) > 0 {
		g.P("FieldWeights: []", ident("FieldWeight"), "{")
		for _, fi := range weighted {
			g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fi.name), ", Weight: ", fmt.Sprintf("%g", fi.opts.Weight), ", Similarity: ", similarityIdent(fi.opts.Similarity), "},")
		}
		g.P("},")
	}

	// --- ConflictStrategies ---
	var conflicted []fieldInfo
	for _, fi := range fields {
		if fi.opts.ConflictStrategy != entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED {
			conflicted = append(conflicted, fi)
		}
	}
	if len(conflicted) > 0 {
		g.P("ConflictStrategies: map[string]", ident("ConflictStrategy"), "{")
		for _, fi := range conflicted {
			g.P(fmt.Sprintf("%q", fi.name), ": ", conflictIdent(fi.opts.ConflictStrategy), ",")
		}
		g.P("},")
	}

	// --- Thresholds ---
	if msgOpts != nil && msgOpts.MatchThresholds != nil {
		mt := msgOpts.MatchThresholds
		g.P("Thresholds: ", ident("MatchThresholds"), "{")
		g.P("AutoMatch: ", fmt.Sprintf("%g", mt.AutoMatch), ",")
		g.P("ReviewZone: ", fmt.Sprintf("%g", mt.ReviewZone), ",")
		g.P("},")
	} else {
		g.P("Thresholds: ", ident("DefaultMatchThresholds"), "(),")
	}

	// --- EmbedFields ---
	var embedFields []string
	for _, fi := range fields {
		if fi.opts.Embed {
			embedFields = append(embedFields, fi.name)
		}
	}
	if len(embedFields) > 0 {
		g.P("EmbedFields: []string{", formatStrings(embedFields), "},")
	}

	// --- TokenFields ---
	var tokenFields []string
	for _, fi := range fields {
		if fi.opts.TokenField {
			tokenFields = append(tokenFields, fi.name)
		}
	}
	if len(tokenFields) > 0 {
		g.P("TokenFields: []string{", formatStrings(tokenFields), "},")
	}

	// --- AllowedRelations ---
	if msgOpts != nil && len(msgOpts.AllowedRelations) > 0 {
		g.P("AllowedRelations: []string{", formatStrings(msgOpts.AllowedRelations), "},")
	}

	// --- Normalizers ---
	var normalized []fieldInfo
	for _, fi := range fields {
		if fi.opts.Normalizer != entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED {
			normalized = append(normalized, fi)
		}
	}
	if len(normalized) > 0 {
		g.P("Normalizers: map[string]func(string) string{")
		for _, fi := range normalized {
			g.P(fmt.Sprintf("%q", fi.name), ": ", normalizerIdent(fi.opts.Normalizer), ",")
		}
		g.P("},")
	}

	g.P("}") // end return
	g.P("}") // end func
	g.P()
}

func similarityIdent(sf entitystorev1.SimilarityFunction) any {
	switch sf {
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_EXACT:
		return ident("SimilarityExact")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_JARO_WINKLER:
		return ident("SimilarityJaroWinkler")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_LEVENSHTEIN:
		return ident("SimilarityLevenshtein")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_TOKEN_JACCARD:
		return ident("SimilarityTokenJaccard")
	default:
		return ident("SimilarityExact")
	}
}

func conflictIdent(cs entitystorev1.ConflictStrategy) any {
	switch cs {
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_FLAG_FOR_REVIEW:
		return ident("ConflictFlagForReview")
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_LATEST_WINS:
		return ident("ConflictLatestWins")
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_HIGHEST_CONFIDENCE:
		return ident("ConflictHighestConf")
	default:
		return ident("ConflictFlagForReview")
	}
}

func normalizerIdent(n entitystorev1.Normalizer) any {
	switch n {
	case entitystorev1.Normalizer_NORMALIZER_LOWERCASE_TRIM:
		return ident("NormalizeLowercaseTrim")
	case entitystorev1.Normalizer_NORMALIZER_PHONE_NORMALIZE:
		return ident("NormalizePhone")
	default:
		return "nil"
	}
}

func formatStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

// ---------------------------------------------------------------------------
// Extraction schema generation
// ---------------------------------------------------------------------------

func generateExtractionSchema(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName
	entityType := string(msg.Desc.FullName())
	msgOpts := getMessageOptions(msg)

	// Collect extractable fields: annotated fields where extract != false,
	// plus all unannotated fields (which are extractable by default).
	type extractField struct {
		name        string
		description string
		hint        string
		required    bool
		repeated    bool
		fieldType   string // ExtractionFieldType constant name
		examples    []string
	}

	var fields []extractField
	for _, f := range msg.Fields {
		fo := getFieldOptions(f)

		// If annotated and explicitly opted out of extraction, skip.
		if fo != nil && fo.Extract != nil && !*fo.Extract {
			continue
		}

		ef := extractField{
			name:      string(f.Desc.Name()),
			repeated:  f.Desc.IsList(),
			fieldType: protoKindToExtractionType(f),
		}

		// Description resolution: annotation > leading comment > humanized name.
		if fo != nil && fo.Description != "" {
			ef.description = fo.Description
		} else if comment := cleanComment(string(f.Comments.Leading)); comment != "" {
			ef.description = comment
		} else {
			ef.description = humanizeFieldName(ef.name)
		}

		if fo != nil {
			ef.hint = fo.ExtractionHint
			ef.required = fo.Anchor
			ef.examples = fo.Examples
		}

		fields = append(fields, ef)
	}

	// Resolve display name: annotation > message name.
	displayName := msgName
	if msgOpts != nil && msgOpts.ExtractionDisplayName != "" {
		displayName = msgOpts.ExtractionDisplayName
	}

	g.P("// ", msgName, "ExtractionSchema returns the proto-annotation-derived extraction")
	g.P("// schema for ", entityType, ".")
	g.P("func ", msgName, "ExtractionSchema() ", extractionIdent("ExtractionSchema"), " {")
	g.P("return ", extractionIdent("ExtractionSchema"), "{")
	g.P("EntityType: ", fmt.Sprintf("%q", entityType), ",")
	g.P("DisplayName: ", fmt.Sprintf("%q", displayName), ",")

	if msgOpts != nil && msgOpts.ExtractionPrompt != "" {
		g.P("Prompt: ", fmt.Sprintf("%q", msgOpts.ExtractionPrompt), ",")
	}
	if msgOpts != nil && msgOpts.ExtractionInstructions != "" {
		g.P("Instructions: ", fmt.Sprintf("%q", msgOpts.ExtractionInstructions), ",")
	}

	g.P("Fields: []", extractionIdent("ExtractionField"), "{")
	for _, ef := range fields {
		g.P("{")
		g.P("Name: ", fmt.Sprintf("%q", ef.name), ",")
		g.P("Description: ", fmt.Sprintf("%q", ef.description), ",")
		if ef.hint != "" {
			g.P("Hint: ", fmt.Sprintf("%q", ef.hint), ",")
		}
		g.P("Type: ", extractionIdent(ef.fieldType), ",")
		if ef.required {
			g.P("Required: true,")
		}
		if ef.repeated {
			g.P("Repeated: true,")
		}
		if len(ef.examples) > 0 {
			g.P("Examples: []string{", formatStrings(ef.examples), "},")
		}
		g.P("},")
	}
	g.P("},")

	g.P("}") // end return
	g.P("}") // end func
	g.P()
}

// protoKindToExtractionType maps a proto field's kind to an ExtractionFieldType constant name.
func protoKindToExtractionType(f *protogen.Field) string {
	switch f.Desc.Kind().String() {
	case "float", "double", "int32", "int64", "uint32", "uint64", "sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64":
		return "ExtractionFieldTypeNumber"
	case "bool":
		return "ExtractionFieldTypeBoolean"
	default:
		return "ExtractionFieldTypeString"
	}
}

// cleanComment trims whitespace and the leading "// " prefix sequences that
// protogen includes in comment strings.
func cleanComment(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	// protogen leading comments include "// " prefixes and trailing newlines.
	// Strip them and join into a single line.
	var parts []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "//")
		line = strings.TrimPrefix(line, " ")
		line = strings.TrimSpace(line)
		if line != "" {
			parts = append(parts, line)
		}
	}
	result := strings.Join(parts, " ")
	// Remove trailing period for consistency — the description is used as a label.
	result = strings.TrimSuffix(result, ".")
	return result
}

// humanizeFieldName converts a snake_case field name to a human-readable label.
// e.g., "full_name" → "full name", "date_of_birth" → "date of birth".
func humanizeFieldName(name string) string {
	return strings.ReplaceAll(name, "_", " ")
}

// ---------------------------------------------------------------------------
// Token extraction generation
// ---------------------------------------------------------------------------

// annotatedFieldsEx collects all annotated fields with their protogen field references.
func annotatedFieldsEx(msg *protogen.Message) []fieldInfoEx {
	var fields []fieldInfoEx
	for _, f := range msg.Fields {
		fo := getFieldOptions(f)
		if fo != nil {
			fields = append(fields, fieldInfoEx{
				fieldInfo: fieldInfo{name: string(f.Desc.Name()), opts: fo},
				field:     f,
			})
		}
	}
	return fields
}

func generateTokens(g *protogen.GeneratedFile, msg *protogen.Message) {
	fields := annotatedFieldsEx(msg)
	var tokenFields []fieldInfoEx
	for _, fi := range fields {
		if fi.opts.TokenField {
			tokenFields = append(tokenFields, fi)
		}
	}
	if len(tokenFields) == 0 {
		return
	}

	msgName := msg.GoIdent.GoName

	g.P("// ", msgName, "Tokens extracts search tokens from the proto message.")
	g.P("// Generated from fields annotated with token_field: true.")
	g.P("func ", msgName, "Tokens(msg *", msg.GoIdent, ") map[string][]string {")
	g.P("tokens := make(map[string][]string)")
	for _, fi := range tokenFields {
		getter := "Get" + fi.field.GoName
		g.P("if v := msg.", getter, "(); v != \"\" {")
		g.P("tokens[", fmt.Sprintf("%q", fi.name), "] = ", ident("Tokenize"), "(v)")
		g.P("}")
	}
	g.P("return tokens")
	g.P("}")
	g.P()
}

// ---------------------------------------------------------------------------
// Embed text generation
// ---------------------------------------------------------------------------

func generateEmbedText(g *protogen.GeneratedFile, msg *protogen.Message) {
	fields := annotatedFieldsEx(msg)
	var embedFields []fieldInfoEx
	for _, fi := range fields {
		if fi.opts.Embed {
			embedFields = append(embedFields, fi)
		}
	}
	if len(embedFields) == 0 {
		return
	}

	msgName := msg.GoIdent.GoName
	stringsJoin := protogen.GoIdent{GoName: "Join", GoImportPath: "strings"}

	g.P("// ", msgName, "EmbedText returns the concatenated text from fields")
	g.P("// annotated with embed: true, suitable for embedding model input.")
	g.P("// Field ordering follows proto field numbers for deterministic output.")
	g.P("func ", msgName, "EmbedText(msg *", msg.GoIdent, ") string {")
	g.P("var parts []string")
	for _, fi := range embedFields {
		getter := "Get" + fi.field.GoName
		g.P("if v := msg.", getter, "(); v != \"\" {")
		g.P("parts = append(parts, v)")
		g.P("}")
	}
	g.P("return ", stringsJoin, "(parts, \" \")")
	g.P("}")
	g.P()
}

// ---------------------------------------------------------------------------
// Anchor extraction generation
// ---------------------------------------------------------------------------

func generateAnchors(g *protogen.GeneratedFile, msg *protogen.Message) {
	fields := annotatedFieldsEx(msg)
	msgOpts := getMessageOptions(msg)

	var singleAnchors []fieldInfoEx
	for _, fi := range fields {
		if fi.opts.Anchor {
			singleAnchors = append(singleAnchors, fi)
		}
	}

	hasComposites := msgOpts != nil && len(msgOpts.CompositeAnchors) > 0
	if len(singleAnchors) == 0 && !hasComposites {
		return
	}

	msgName := msg.GoIdent.GoName
	lowerName := strings.ToLower(msgName[:1]) + msgName[1:]

	g.P("// ", lowerName, "Anchors extracts anchor queries from the proto message.")
	g.P("// Generated from fields annotated with anchor: true and composite_anchors.")
	g.P("func ", lowerName, "Anchors(msg *", msg.GoIdent, ") []", ident("AnchorQuery"), " {")
	g.P("var anchors []", ident("AnchorQuery"))

	// Single anchors.
	for _, fi := range singleAnchors {
		getter := "Get" + fi.field.GoName
		g.P("if v := msg.", getter, "(); v != \"\" {")
		if fi.opts.Normalizer != entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED {
			g.P("v = ", normalizerIdent(fi.opts.Normalizer), "(v)")
		}
		g.P("anchors = append(anchors, ", ident("AnchorQuery"), "{Field: ", fmt.Sprintf("%q", fi.name), ", Value: v})")
		g.P("}")
	}

	// Composite anchors.
	if hasComposites {
		// Build a lookup of field name → fieldInfoEx for getter access.
		fieldMap := make(map[string]fieldInfoEx)
		for _, fi := range fields {
			fieldMap[fi.name] = fi
		}

		for _, ca := range msgOpts.CompositeAnchors {
			// Generate: if all fields are non-empty, build composite.
			var conditions []string
			for _, fn := range ca.Fields {
				if fi, ok := fieldMap[fn]; ok {
					conditions = append(conditions, fmt.Sprintf("msg.Get%s() != \"\"", fi.field.GoName))
				}
			}
			if len(conditions) > 0 {
				g.P("if ", strings.Join(conditions, " && "), " {")
				g.P("var compositeVal string")
				for i, fn := range ca.Fields {
					if fi, ok := fieldMap[fn]; ok {
						getter := "Get" + fi.field.GoName
						if i == 0 {
							if fi.opts.Normalizer != entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED {
								g.P("compositeVal = ", normalizerIdent(fi.opts.Normalizer), "(msg.", getter, "())")
							} else {
								g.P("compositeVal = msg.", getter, "()")
							}
						} else {
							if fi.opts.Normalizer != entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED {
								g.P("compositeVal += \"|\" + ", normalizerIdent(fi.opts.Normalizer), "(msg.", getter, "())")
							} else {
								g.P("compositeVal += \"|\" + msg.", getter, "()")
							}
						}
					}
				}
				compositeField := strings.Join(ca.Fields, "+")
				g.P("anchors = append(anchors, ", ident("AnchorQuery"), "{Field: ", fmt.Sprintf("%q", compositeField), ", Value: compositeVal})")
				g.P("}")
			}
		}
	}

	g.P("return anchors")
	g.P("}")
	g.P()
}

// ---------------------------------------------------------------------------
// WriteOp generation
// ---------------------------------------------------------------------------
// Display name generation
// ---------------------------------------------------------------------------

func generateDisplayName(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgOpts := getMessageOptions(msg)
	if msgOpts == nil || len(msgOpts.DisplayFields) == 0 {
		return
	}

	fields := annotatedFieldsEx(msg)
	fieldMap := make(map[string]fieldInfoEx)
	for _, fi := range fields {
		fieldMap[fi.name] = fi
	}
	// Also include unannotated fields for display_fields.
	for _, f := range msg.Fields {
		name := string(f.Desc.Name())
		if _, ok := fieldMap[name]; !ok {
			fieldMap[name] = fieldInfoEx{
				fieldInfo: fieldInfo{name: name},
				field:     f,
			}
		}
	}

	msgName := msg.GoIdent.GoName

	g.P("// ", msgName, "DisplayName returns a human-readable display name from the message.")
	g.P("// Uses the first non-empty field from display_fields annotation.")
	g.P("func ", msgName, "DisplayName(msg *", msg.GoIdent, ") string {")
	for _, fieldName := range msgOpts.DisplayFields {
		if fi, ok := fieldMap[fieldName]; ok {
			getter := "Get" + fi.field.GoName
			g.P("if v := msg.", getter, "(); v != \"\" {")
			g.P("return v")
			g.P("}")
		}
	}
	g.P("return \"\"")
	g.P("}")
	g.P()
}

// ---------------------------------------------------------------------------
// WriteOp generation
// ---------------------------------------------------------------------------

func generateWriteOp(g *protogen.GeneratedFile, msg *protogen.Message) {
	fields := annotatedFieldsEx(msg)
	msgOpts := getMessageOptions(msg)

	// Only generate WriteOp if there's at least one anchor or token field.
	hasAnchors := false
	hasTokens := false
	for _, fi := range fields {
		if fi.opts.Anchor {
			hasAnchors = true
		}
		if fi.opts.TokenField {
			hasTokens = true
		}
	}
	hasComposites := msgOpts != nil && len(msgOpts.CompositeAnchors) > 0
	if !hasAnchors && !hasTokens && !hasComposites {
		return
	}

	msgName := msg.GoIdent.GoName
	lowerName := strings.ToLower(msgName[:1]) + msgName[1:]

	g.P("// ", msgName, "WriteOp builds a WriteEntityOp with all proto annotations applied.")
	g.P("// Anchors, tokens, and data are wired automatically from the message.")
	g.P("func ", msgName, "WriteOp(msg *", msg.GoIdent, ", action ", storeIdent("WriteAction"), ", opts ...", storeIdent("WriteOpOption"), ") *", storeIdent("WriteEntityOp"), " {")
	g.P("op := &", storeIdent("WriteEntityOp"), "{")
	g.P("Action: action,")
	g.P("Data: msg,")
	g.P("Confidence: 1.0,")

	if hasAnchors || hasComposites {
		g.P("Anchors: ", lowerName, "Anchors(msg),")
	}
	if hasTokens {
		g.P("Tokens: ", msgName, "Tokens(msg),")
	}

	hasDisplayFields := msgOpts != nil && len(msgOpts.DisplayFields) > 0
	if hasDisplayFields {
		g.P("DisplayName: ", msgName, "DisplayName(msg),")
	}

	g.P("}")
	g.P("for _, o := range opts {")
	g.P("o(op)")
	g.P("}")
	g.P("return op")
	g.P("}")
	g.P()
}
