// Command protoc-gen-entitystore is a protoc/buf plugin that reads
// entitystore.v1 field and message options and generates Go code that
// returns a matching.EntityMatchConfig for each annotated message.
package main

import (
	"fmt"
	"strings"

	entitystorev1 "github.com/laenen-partners/entitystore/gen/entitystore/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const matchingPkg = "github.com/laenen-partners/entitystore/matching"

func ident(name string) protogen.GoIdent {
	return protogen.GoIdent{
		GoName:       name,
		GoImportPath: protogen.GoImportPath(matchingPkg),
	}
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	var annotated []*protogen.Message
	for _, msg := range file.Messages {
		if hasAnnotations(msg) {
			annotated = append(annotated, msg)
		}
	}
	if len(annotated) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_entitystore.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-entitystore. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, msg := range annotated {
		generateMatchConfig(g, msg)
	}

	return nil
}

func hasAnnotations(msg *protogen.Message) bool {
	if getMessageOptions(msg) != nil {
		return true
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field) != nil {
			return true
		}
	}
	return false
}

func getMessageOptions(msg *protogen.Message) *entitystorev1.MessageOptions {
	opts := msg.Desc.Options().(*descriptorpb.MessageOptions)
	if opts == nil {
		return nil
	}
	ext, ok := proto.GetExtension(opts, entitystorev1.E_Message).(*entitystorev1.MessageOptions)
	if !ok || ext == nil {
		return nil
	}
	return ext
}

func getFieldOptions(field *protogen.Field) *entitystorev1.FieldOptions {
	opts := field.Desc.Options().(*descriptorpb.FieldOptions)
	if opts == nil {
		return nil
	}
	ext, ok := proto.GetExtension(opts, entitystorev1.E_Field).(*entitystorev1.FieldOptions)
	if !ok || ext == nil {
		return nil
	}
	return ext
}

type fieldInfo struct {
	name string
	opts *entitystorev1.FieldOptions
}

func generateMatchConfig(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName
	entityType := string(msg.Desc.FullName())

	var fields []fieldInfo
	for _, f := range msg.Fields {
		fo := getFieldOptions(f)
		if fo != nil {
			fields = append(fields, fieldInfo{
				name: string(f.Desc.Name()),
				opts: fo,
			})
		}
	}

	msgOpts := getMessageOptions(msg)

	g.P("// ", msgName, "MatchConfig returns the proto-annotation-derived matching")
	g.P("// configuration for ", entityType, ".")
	g.P("func ", msgName, "MatchConfig() ", ident("EntityMatchConfig"), " {")
	g.P("return ", ident("EntityMatchConfig"), "{")
	g.P("EntityType: ", fmt.Sprintf("%q", entityType), ",")

	// --- Anchors ---
	g.P("Anchors: ", ident("AnchorConfig"), "{")

	var singleAnchors []fieldInfo
	for _, fi := range fields {
		if fi.opts.Anchor {
			singleAnchors = append(singleAnchors, fi)
		}
	}
	if len(singleAnchors) > 0 {
		g.P("SingleAnchors: []", ident("AnchorField"), "{")
		for _, fi := range singleAnchors {
			g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fi.name), ", Normalizer: ", normalizerIdent(fi.opts.Normalizer), "},")
		}
		g.P("},")
	}

	if msgOpts != nil && len(msgOpts.CompositeAnchors) > 0 {
		g.P("CompositeAnchors: [][]", ident("AnchorField"), "{")
		for _, ca := range msgOpts.CompositeAnchors {
			g.P("{")
			for _, fieldName := range ca.Fields {
				norm := entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED
				for _, fi := range fields {
					if fi.name == fieldName {
						norm = fi.opts.Normalizer
						break
					}
				}
				g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fieldName), ", Normalizer: ", normalizerIdent(norm), "},")
			}
			g.P("},")
		}
		g.P("},")
	}
	g.P("},") // end Anchors

	// --- FieldWeights ---
	var weighted []fieldInfo
	for _, fi := range fields {
		if fi.opts.Weight > 0 {
			weighted = append(weighted, fi)
		}
	}
	if len(weighted) > 0 {
		g.P("FieldWeights: []", ident("FieldWeight"), "{")
		for _, fi := range weighted {
			g.P("{ProtoFieldName: ", fmt.Sprintf("%q", fi.name), ", Weight: ", fmt.Sprintf("%g", fi.opts.Weight), ", Similarity: ", similarityIdent(fi.opts.Similarity), "},")
		}
		g.P("},")
	}

	// --- ConflictStrategies ---
	var conflicted []fieldInfo
	for _, fi := range fields {
		if fi.opts.ConflictStrategy != entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED {
			conflicted = append(conflicted, fi)
		}
	}
	if len(conflicted) > 0 {
		g.P("ConflictStrategies: map[string]", ident("ConflictStrategy"), "{")
		for _, fi := range conflicted {
			g.P(fmt.Sprintf("%q", fi.name), ": ", conflictIdent(fi.opts.ConflictStrategy), ",")
		}
		g.P("},")
	}

	// --- Thresholds ---
	if msgOpts != nil && msgOpts.MatchThresholds != nil {
		mt := msgOpts.MatchThresholds
		g.P("Thresholds: ", ident("MatchThresholds"), "{")
		g.P("AutoMatch: ", fmt.Sprintf("%g", mt.AutoMatch), ",")
		g.P("ReviewZone: ", fmt.Sprintf("%g", mt.ReviewZone), ",")
		g.P("},")
	} else {
		g.P("Thresholds: ", ident("DefaultMatchThresholds"), "(),")
	}

	// --- EmbedFields ---
	var embedFields []string
	for _, fi := range fields {
		if fi.opts.Embed {
			embedFields = append(embedFields, fi.name)
		}
	}
	if len(embedFields) > 0 {
		g.P("EmbedFields: []string{", formatStrings(embedFields), "},")
	}

	// --- TokenFields ---
	var tokenFields []string
	for _, fi := range fields {
		if fi.opts.TokenField {
			tokenFields = append(tokenFields, fi.name)
		}
	}
	if len(tokenFields) > 0 {
		g.P("TokenFields: []string{", formatStrings(tokenFields), "},")
	}

	// --- AllowedRelations ---
	if msgOpts != nil && len(msgOpts.AllowedRelations) > 0 {
		g.P("AllowedRelations: []string{", formatStrings(msgOpts.AllowedRelations), "},")
	}

	// --- Normalizers ---
	var normalized []fieldInfo
	for _, fi := range fields {
		if fi.opts.Normalizer != entitystorev1.Normalizer_NORMALIZER_UNSPECIFIED {
			normalized = append(normalized, fi)
		}
	}
	if len(normalized) > 0 {
		g.P("Normalizers: map[string]func(string) string{")
		for _, fi := range normalized {
			g.P(fmt.Sprintf("%q", fi.name), ": ", normalizerIdent(fi.opts.Normalizer), ",")
		}
		g.P("},")
	}

	g.P("}") // end return
	g.P("}") // end func
	g.P()
}

func similarityIdent(sf entitystorev1.SimilarityFunction) any {
	switch sf {
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_EXACT:
		return ident("SimilarityExact")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_JARO_WINKLER:
		return ident("SimilarityJaroWinkler")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_LEVENSHTEIN:
		return ident("SimilarityLevenshtein")
	case entitystorev1.SimilarityFunction_SIMILARITY_FUNCTION_TOKEN_JACCARD:
		return ident("SimilarityTokenJaccard")
	default:
		return ident("SimilarityExact")
	}
}

func conflictIdent(cs entitystorev1.ConflictStrategy) any {
	switch cs {
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_FLAG_FOR_REVIEW:
		return ident("ConflictFlagForReview")
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_LATEST_WINS:
		return ident("ConflictLatestWins")
	case entitystorev1.ConflictStrategy_CONFLICT_STRATEGY_HIGHEST_CONFIDENCE:
		return ident("ConflictHighestConf")
	default:
		return ident("ConflictFlagForReview")
	}
}

func normalizerIdent(n entitystorev1.Normalizer) any {
	switch n {
	case entitystorev1.Normalizer_NORMALIZER_LOWERCASE_TRIM:
		return ident("NormalizeLowercaseTrim")
	case entitystorev1.Normalizer_NORMALIZER_PHONE_NORMALIZE:
		return ident("NormalizePhone")
	default:
		return "nil"
	}
}

func formatStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
